using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APM.Models.Tools
{
    public class Icon
    {

        public static List<SelectListItem> KendoIcon()
        { 
            if(HttpContext.Current.Session["CachedIconList"]==null)
            {

                string[] IconArr ={"caret-tr",
    "caret-br",
    "caret-bl",
    "caret-tl",
    "caret-alt-up",
    "caret-alt-right",
    "caret-alt-down",
    "caret-alt-left",
    "caret-alt-to-top",
    "caret-alt-to-right",
    "caret-alt-to-bottom",
    "caret-alt-to-left",
    "caret-double-alt-up",
    "caret-double-alt-right",
    "caret-double-alt-down",
    "caret-double-alt-left",
    "caret-alt-expand",
    "arrows-no-change",
    "arrow-overflow-down",
    "chevron-up",
    "chevron-right",
    "chevron-down",
    "chevron-left",
    "arrow-up",
    "arrow-right",
    "arrow-down",
    "arrow-left",
    "level-down",
    "level-up",
    "level-to-top",
    "col-resize",
    "arrows-axes",
    "arrows-swap",
    "drag-and-drop",
    "categorize",
    "grid",
    "grid-layout",
    "group",
    "ungroup",
    "handle-drag",
    "layout",
    "layout-1-by-4",
    "layout-2-by-2",
    "layout-side-by-side",
    "layout-stacked",
    "columns",
    "rows",
    "reorder",
    "menu",
    "more-vertical",
    "more-horizontal",
    "overlap",
    "home",
    "arrows-left-right",
    "arrows-top-bottom",
    "border-radius-bottom-left",
    "border-radius-bottom-right",
    "border-radius-top-left",
    "border-radius-top-right",
    "border-radius",
    "border-style-bottom",
    "border-style-left",
    "border-style-right",
    "border-style-top",
    "border-style",
    "box-sizing",
    "chevron-double-down",
    "chevron-double-left",
    "chevron-double-right",
    "chevron-double-up",
    "data-ods",
    "display-Inline-block",
    "display-block",
    "display-flex",
    "display-inline-flex",
    "droplet-slider",
    "file-report",
    "gap-column",
    "gap-row",
    "handle-resize-alt",
    "handle-resize",
    "images",
    "letter-space",
    "line-height",
    "list-latin-big",
    "list-latin-small",
    "list-roman-big",
    "list-roman-small",
    "list-unordered-outline",
    "list-unordered-square",
    "max-height",
    "max-width",
    "min-height",
    "min-width",
    "outline-offset",
    "outline-width",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
    "padding",
    "position-bottom",
    "position-left",
    "position-right",
    "position-top",
    "regular-expression",
    "replace-all",
    "replace-single",
    "report-element",
    "right-double-quotes",
    "whole-word",
    "undo",
    "redo",
    "arrow-rotate-ccw",
    "arrow-rotate-cw",
    "arrows-no-repeat",
    "arrow-rotate-ccw-small",
    "arrow-rotate-cw-small",
    "clock",
    "calendar",
    "save",
    "print",
    "pencil",
    "trash",
    "paperclip",
    "paperclip-alt",
    "link",
    "unlink",
    "link-vertical",
    "unlink-vertical",
    "lock",
    "unlock",
    "cancel",
    "cancel-outline",
    "cancel-circle",
    "check",
    "check-outline",
    "check-circle",
    "x",
    "x-outline",
    "x-circle",
    "plus",
    "plus-outline",
    "plus-circle",
    "minus",
    "minus-outline",
    "minus-circle",
    "sort-asc",
    "sort-desc",
    "sort-clear",
    "sort-asc-small",
    "sort-desc-small",
    "filter",
    "filter-clear",
    "filter-small",
    "filter-sort-asc-small",
    "filter-sort-desc-small",
    "filter-add-expression",
    "filter-add-group",
    "login",
    "logout",
    "download",
    "upload",
    "hyperlink-open",
    "hyperlink-open-sm",
    "launch",
    "window",
    "window-restore",
    "window-minimize",
    "gear",
    "gears",
    "wrench",
    "eye",
    "search",
    "zoom-in",
    "zoom-out",
    "arrows-move",
    "calculator",
    "cart",
    "connector",
    "plus-sm",
    "minus-sm",
    "kpi-status-deny",
    "kpi-status-hold",
    "kpi-status-open",
    "equal",
    "not-equal",
    "less-or-equal",
    "greater-or-equal",
    "divide",
    "accessibility",
    "barcode-outline",
    "barcode",
    "barcode-scanner",
    "qr-code-outline",
    "qr-code",
    "qr-code-scanner",
    "barcode-qr-code-scanner",
    "signature",
    "hand",
    "pointer",
    "stick",
    "unstick",
    "set-column-position",
    "clock-arrow-rotate",
    "play",
    "pause",
    "stop",
    "rewind",
    "forward",
    "volume-down",
    "volume-up",
    "volume-mute",
    "hd",
    "closed-captions",
    "playlist",
    "music-notes",
    "play-sm",
    "pause-sm",
    "stop-sm",
    "heart-outline",
    "heart",
    "star-outline",
    "star",
    "checkbox",
    "checkbox-checked",
    "checkbox-indeterminate",
    "checkbox-null",
    "circle",
    "radiobutton",
    "radiobutton-checked",
    "bell",
    "info-circle",
    "question-circle",
    "exclamation-circle",
    "camera",
    "image",
    "image-export",
    "zoom-actual-size",
    "zoom-best-fit",
    "image-resize",
    "crop",
    "mirror",
    "flip-horizontal",
    "flip-vertical",
    "rotate",
    "rotate-right",
    "rotate-left",
    "brush",
    "palette",
    "droplet",
    "shape-line",
    "brightness-contrast",
    "sliders",
    "invert-colors",
    "transparency",
    "grayscale",
    "blur",
    "sharpen",
    "shapes",
    "round-corners",
    "bring-to-front",
    "bring-to-back",
    "bring-forward",
    "bring-backward",
    "align-self-start",
    "align-self-center",
    "align-self-end",
    "align-self-start-alt",
    "align-self-center-alt",
    "align-self-end-alt",
    "thumbnails-up",
    "thumbnails-right",
    "thumbnails-down",
    "thumbnails-left",
    "fullscreen",
    "fullscreen-exit",
    "droplet-slash",
    "photos",
    "align-to-grid",
    "size-to-grid",
    "make-same-size",
    "make-same-width",
    "make-same-height",
    "make-horizontal-spacing-equal",
    "increase-horizontal-spacing",
    "decrease-horizontal-spacing",
    "remove-horizontal-spacing",
    "make-vertical-spacing-equal",
    "increase-vertical-spacing",
    "decrease-vertical-spacing",
    "remove-vertical-spacing",
    "eyedropper",
    "snap-grid",
    "snap-to-gridlines",
    "snap-to-snaplines",
    "dimensions",
    "align-self-stretch",
    "align-self-stretch-alt",
    "align-items-start",
    "align-items-center",
    "align-items-end",
    "align-items-stretch",
    "align-items-baseline",
    "align-items-start-alt",
    "align-items-center-alt",
    "align-items-end-alt",
    "align-items-stretch-alt",
    "align-items-baseline-alt",
    "justify-content-start",
    "justify-content-center",
    "justify-content-end",
    "justify-content-between",
    "justify-content-around",
    "justify-content-start-alt",
    "justify-content-center-alt",
    "justify-content-end-alt",
    "justify-content-between-alt",
    "justify-content-around-alt",
    "file-wrench",
    "bold",
    "italic",
    "underline",
    "font-family",
    "foreground-color",
    "convert-lowercase",
    "convert-uppercase",
    "strikethrough",
    "subscript",
    "supscript",
    "div",
    "all",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "list-ordered",
    "list-unordered",
    "indent",
    "outdent",
    "insert-top",
    "insert-middle",
    "insert-bottom",
    "align-top",
    "align-middle",
    "align-bottom",
    "align-left",
    "align-center",
    "align-right",
    "align-justify",
    "align-remove",
    "text-wrap",
    "horizontal-rule",
    "table-align-top-left",
    "table-align-top-center",
    "table-align-top-right",
    "table-align-middle-left",
    "table-align-middle-center",
    "table-align-middle-right",
    "table-align-bottom-left",
    "table-align-bottom-center",
    "table-align-bottom-right",
    "table-align-remove",
    "borders-all",
    "borders-outside",
    "borders-inside",
    "borders-inside-horizontal",
    "borders-inside-vertical",
    "border-top",
    "border-bottom",
    "border-left",
    "border-right",
    "borders-none",
    "borders-show-hide",
    "form",
    "form-element",
    "code-snippet",
    "select-all",
    "button",
    "select-box",
    "calendar-date",
    "group-box",
    "textarea",
    "textbox",
    "textbox-hidden",
    "password",
    "paragraph-add",
    "edit-tools",
    "template-manager",
    "change-manually",
    "track-changes",
    "track-changes-enable",
    "track-changes-accept",
    "track-changes-accept-all",
    "track-changes-reject",
    "track-changes-reject-all",
    "document-manager",
    "custom-icon",
    "book",
    "image-add",
    "image-edit",
    "image-map-editor",
    "comment",
    "comment-remove",
    "comments-remove",
    "silverlight",
    "media-manager",
    "video-external",
    "flash-manager",
    "binoculars",
    "copy",
    "cut",
    "clipboard",
    "clipboard-code",
    "clipboard-word",
    "clipboard-word-alt",
    "clipboard-html",
    "clipboard-markdown",
    "clipboard-text",
    "apply-format",
    "clear-css",
    "copy-format",
    "strip-all-formatting",
    "strip-css-format",
    "strip-font-elements",
    "strip-span-elements",
    "strip-word-formatting",
    "format-code-block",
    "building-blocks",
    "puzzle-piece",
    "link-add",
    "globe-link",
    "globe-unlink",
    "envelop-link",
    "anchor",
    "table-add",
    "table",
    "table-properties",
    "table-cell",
    "table-cell-properties",
    "table-column-insert-left",
    "table-column-insert-right",
    "table-row-insert-above",
    "table-row-insert-below",
    "table-column-delete",
    "table-row-delete",
    "table-cell-delete",
    "table-delete",
    "cells-merge",
    "cells-merge-horizontally",
    "cells-merge-vertically",
    "cell-split-horizontally",
    "cell-split-vertically",
    "table-unmerge",
    "pane-freeze",
    "row-freeze",
    "column-freeze",
    "toolbar-float",
    "spell-checker",
    "validation-xhtml",
    "validation-data",
    "toggle-full-screen-mode",
    "formula-fx",
    "sum",
    "symbol",
    "dollar",
    "percent",
    "custom-format",
    "decimal-increase",
    "decimal-decrease",
    "font-size",
    "image-absolute-position",
    "table-wizard",
    "crosstab",
    "crosstab-wizard",
    "table-body",
    "table-column-groups",
    "table-corner",
    "table-row-groups",
    "globe-outline",
    "globe",
    "map-marker",
    "map-marker-target",
    "pin",
    "unpin",
    "share",
    "user",
    "inbox",
    "blogger",
    "blogger-box",
    "delicious",
    "delicious-box",
    "digg",
    "digg-box",
    "envelop",
    "envelop-box",
    "facebook",
    "facebook-box",
    "google",
    "google-box",
    "google-plus",
    "google-plus-box",
    "linkedin",
    "linkedin-box",
    "myspace",
    "myspace-box",
    "pinterest",
    "pinterest-box",
    "reddit",
    "reddit-box",
    "stumble-upon",
    "stumble-upon-box",
    "tell-a-friend",
    "tell-a-friend-box",
    "tumblr",
    "tumblr-box",
    "twitter",
    "twitter-box",
    "yammer",
    "yammer-box",
    "behance",
    "behance-box",
    "dribbble",
    "dribbble-box",
    "rss",
    "rss-box",
    "vimeo",
    "vimeo-box",
    "youtube",
    "youtube-box",
    "folder",
    "folder-open",
    "folder-add",
    "folder-up",
    "folder-more",
    "aggregate-fields",
    "file",
    "file-add",
    "file-txt",
    "file-csv",
    "file-excel",
    "file-word",
    "file-mdb",
    "file-ppt",
    "file-pdf",
    "file-psd",
    "file-flash",
    "file-config",
    "file-ascx",
    "file-bac",
    "file-zip",
    "film",
    "css3",
    "html5",
    "code",
    "css",
    "js",
    "exe",
    "csproj",
    "vbproj",
    "cs",
    "vb",
    "sln",
    "cloud",
    "file-horizontal",
    "subreport",
    "data",
    "file-header",
    "file-footer",
    "group-header-section",
    "group-footer-section",
    "page-header-section",
    "page-footer-section",
    "detail-section",
    "toc-section",
    "group-section",
    "parameters",
    "data-csv",
    "data-json",
    "data-sql",
    "data-web",
    "group-collection",
    "parameter-boolean",
    "parameter-date-time",
    "parameter-float",
    "parameter-integer",
    "parameter-string",
    "toc-section-level",
    "inherited",
    "file-video",
    "file-audio",
    "file-image",
    "file-presentation",
    "file-data",
    "file-disc-image",
    "file-programming",
    "parameters-byte-array",
    "parameters-unknown",
    "file-error",
    "files-error",
    "data-rest",
    "file-typescript",
    "table-position-start",
    "table-position-center",
    "table-position-end",
    "list-roman-upper",
    "list-roman-lower",
    "import",
    "export",
    "graph",
    "chart-column-clustered",
    "chart-column-stacked",
    "chart-column-stacked100",
    "chart-column-range",
    "chart-bar-clustered",
    "chart-bar-stacked",
    "chart-bar-stacked100",
    "chart-bar-range",
    "chart-area-clustered",
    "chart-area-stacked",
    "chart-area-stacked100",
    "chart-area-range",
    "chart-line",
    "chart-line-stacked",
    "chart-line-stacked100",
    "chart-line-markers",
    "chart-line-stacked-markers",
    "chart-line-stacked100-markers",
    "chart-pie",
    "chart-doughnut",
    "chart-scatter",
    "chart-scatter-smooth-lines-markers",
    "chart-scatter-smooth-lines",
    "chart-scatter-straight-lines-markers",
    "chart-scatter-straight-lines",
    "chart-bubble",
    "chart-candlestick",
    "chart-ohlc",
    "chart-radar",
    "chart-radar-markers",
    "chart-radar-filled",
    "chart-rose",
    "chart-choropleth"};
                List<SelectListItem> IconList = new List<SelectListItem>();
                foreach (string Item in IconArr)
                {
                    IconList.Add(new SelectListItem() { Text = "k-i-" + Item, Value = "k-icon k-i-" + Item });
                }
                string Font = @"fa-pull-left,fa-pull-right,fa-beat,fa-fade,fa-flash,fa-flip,fa-spin,fa-spin-reverse,fa-pulse,fa-spin-pulse,fa-rotate-90,fa-rotate-180,fa-rotate-270,fa-flip-horizontal,fa-flip-vertical,fa-flip-both,fa-rotate-by,fa-stack,fa-stack-1x,fa-stack-2x,fa-inverse,fa-0,fa-1,fa-2,fa-3,fa-4,fa-5,fa-6,fa-7,fa-8,fa-9,fa-360-degrees,fa-a,fa-abacus,fa-accent-grave,fa-acorn,fa-address-book,fa-contact-book,fa-address-card,fa-contact-card,fa-vcard,fa-air-conditioner,fa-airplay,fa-alarm-clock,fa-alarm-exclamation,fa-alarm-plus,fa-alarm-snooze,fa-album,fa-album-collection,fa-alicorn,fa-alien,fa-alien-8bit,fa-alien-monster,fa-align-center,fa-align-justify,fa-align-left,fa-align-right,fa-align-slash,fa-alt,fa-amp-guitar,fa-ampersand,fa-anchor,fa-angel,fa-angle,fa-angle-90,fa-angle-down,fa-angle-left,fa-angle-right,fa-angle-up,fa-angle-double-down,fa-angles-down,fa-angle-double-left,fa-angles-left,fa-angle-double-right,fa-angles-right,fa-angle-double-up,fa-angles-up,fa-ankh,fa-aperture,fa-apostrophe,fa-apple-core,fa-apple-alt,fa-apple-whole,fa-archway,fa-arrow-down,fa-arrow-down-1-9,fa-sort-numeric-asc,fa-sort-numeric-down,fa-arrow-down-9-1,fa-sort-numeric-desc,fa-sort-numeric-down-alt,fa-arrow-down-a-z,fa-sort-alpha-asc,fa-sort-alpha-down,fa-arrow-down-arrow-up,fa-sort-alt,fa-arrow-down-big-small,fa-sort-size-down,fa-arrow-down-from-dotted-line,fa-arrow-down-from-line,fa-arrow-from-top,fa-arrow-down-left,fa-arrow-down-left-and-arrow-up-right-to-center,fa-arrow-down-long,fa-long-arrow-down,fa-arrow-down-right,fa-arrow-down-short-wide,fa-sort-amount-desc,fa-sort-amount-down-alt,fa-arrow-down-small-big,fa-sort-size-down-alt,fa-arrow-down-square-triangle,fa-sort-shapes-down-alt,fa-arrow-down-to-bracket,fa-arrow-down-to-dotted-line,fa-arrow-down-to-line,fa-arrow-to-bottom,fa-arrow-down-to-square,fa-arrow-down-triangle-square,fa-sort-shapes-down,fa-arrow-down-wide-short,fa-sort-amount-asc,fa-sort-amount-down,fa-arrow-down-z-a,fa-sort-alpha-desc,fa-sort-alpha-down-alt,fa-arrow-left,fa-arrow-from-right,fa-arrow-left-from-line,fa-arrow-left-long,fa-long-arrow-left,fa-arrow-left-to-line,fa-arrow-to-left,fa-arrow-pointer,fa-mouse-pointer,fa-arrow-right,fa-arrow-right-arrow-left,fa-exchange,fa-arrow-right-from-bracket,fa-sign-out,fa-arrow-from-left,fa-arrow-right-from-line,fa-arrow-right-long,fa-long-arrow-right,fa-arrow-right-to-bracket,fa-sign-in,fa-arrow-right-to-line,fa-arrow-to-right,fa-arrow-left-rotate,fa-arrow-rotate-back,fa-arrow-rotate-backward,fa-arrow-rotate-left,fa-undo,fa-arrow-right-rotate,fa-arrow-rotate-forward,fa-arrow-rotate-right,fa-redo,fa-arrow-trend-down,fa-arrow-trend-up,fa-arrow-turn-down,fa-level-down,fa-arrow-turn-down-left,fa-arrow-turn-up,fa-level-up,fa-arrow-up,fa-arrow-up-1-9,fa-sort-numeric-up,fa-arrow-up-9-1,fa-sort-numeric-up-alt,fa-arrow-up-a-z,fa-sort-alpha-up,fa-arrow-up-arrow-down,fa-sort-up-down,fa-arrow-up-big-small,fa-sort-size-up,fa-arrow-up-from-bracket,fa-arrow-up-from-dotted-line,fa-arrow-from-bottom,fa-arrow-up-from-line,fa-arrow-up-from-square,fa-arrow-up-left,fa-arrow-up-left-from-circle,fa-arrow-up-long,fa-long-arrow-up,fa-arrow-up-right,fa-arrow-up-right-and-arrow-down-left-from-center,fa-arrow-up-right-from-square,fa-external-link,fa-arrow-up-short-wide,fa-sort-amount-up-alt,fa-arrow-up-small-big,fa-sort-size-up-alt,fa-arrow-up-square-triangle,fa-sort-shapes-up-alt,fa-arrow-up-to-dotted-line,fa-arrow-to-top,fa-arrow-up-to-line,fa-arrow-up-triangle-square,fa-sort-shapes-up,fa-arrow-up-wide-short,fa-sort-amount-up,fa-arrow-up-z-a,fa-sort-alpha-up-alt,fa-arrows-cross,fa-arrows-from-dotted-line,fa-arrows-from-line,fa-arrows-h,fa-arrows-left-right,fa-arrows-maximize,fa-expand-arrows,fa-arrows-minimize,fa-compress-arrows,fa-arrows-repeat,fa-repeat-alt,fa-arrows-repeat-1,fa-repeat-1-alt,fa-arrows-retweet,fa-retweet-alt,fa-arrows-rotate,fa-refresh,fa-sync,fa-arrows-to-dotted-line,fa-arrows-to-line,fa-arrows-up-down,fa-arrows-v,fa-arrows-up-down-left-right,fa-arrows,fa-asterisk,fa-at,fa-atom,fa-atom-alt,fa-atom-simple,fa-audio-description,fa-audio-description-slash,fa-austral-sign,fa-avocado,fa-award,fa-award-simple,fa-axe,fa-axe-battle,fa-b,fa-baby,fa-baby-carriage,fa-carriage-baby,fa-backpack,fa-backward,fa-backward-fast,fa-fast-backward,fa-backward-step,fa-step-backward,fa-bacon,fa-bacteria,fa-bacterium,fa-badge,fa-badge-check,fa-badge-dollar,fa-badge-percent,fa-badge-sheriff,fa-badger-honey,fa-bag-shopping,fa-shopping-bag,fa-bags-shopping,fa-bahai,fa-baht-sign,fa-ball-pile,fa-balloon,fa-balloons,fa-ballot,fa-ballot-check,fa-ban,fa-cancel,fa-ban-bug,fa-debug,fa-ban-parking,fa-parking-circle-slash,fa-ban-smoking,fa-smoking-ban,fa-banana,fa-band-aid,fa-bandage,fa-bangladeshi-taka-sign,fa-banjo,fa-bank,fa-institution,fa-university,fa-barcode,fa-barcode-read,fa-barcode-scan,fa-bars,fa-navicon,fa-bars-filter,fa-bars-progress,fa-tasks-alt,fa-bars-sort,fa-bars-staggered,fa-reorder,fa-stream,fa-baseball-ball,fa-baseball-bat-ball,fa-baseball,fa-basket-shopping,fa-shopping-basket,fa-basket-shopping-simple,fa-shopping-basket-alt,fa-basketball-ball,fa-basketball-hoop,fa-bat,fa-bath,fa-bathtub,fa-battery-bolt,fa-battery-0,fa-battery-empty,fa-battery-exclamation,fa-battery-5,fa-battery-full,fa-battery,fa-battery-3,fa-battery-half,fa-battery-1,fa-battery-low,fa-battery-2,fa-battery-quarter,fa-battery-slash,fa-battery-4,fa-battery-three-quarters,fa-bed,fa-bed-bunk,fa-bed-empty,fa-bed-alt,fa-bed-front,fa-bed-pulse,fa-procedures,fa-bee,fa-beer-foam,fa-beer-mug,fa-beer-mug-empty,fa-beer,fa-bell,fa-bell-concierge,fa-concierge-bell,fa-bell-exclamation,fa-bell-on,fa-bell-plus,fa-bell-school,fa-bell-school-slash,fa-bell-slash,fa-bells,fa-bench-tree,fa-bezier-curve,fa-bicycle,fa-binoculars,fa-biohazard,fa-bitcoin-sign,fa-blanket,fa-blender,fa-blender-phone,fa-blinds,fa-blinds-open,fa-blinds-raised,fa-block-quote,fa-blog,fa-blueberries,fa-bold,fa-bolt,fa-bolt-auto,fa-bolt-lightning,fa-bolt-slash,fa-bomb,fa-bone,fa-bone-break,fa-bong,fa-book,fa-book-arrow-right,fa-book-arrow-up,fa-atlas,fa-book-atlas,fa-bible,fa-book-bible,fa-book-alt,fa-book-blank,fa-book-bookmark,fa-book-circle-arrow-right,fa-book-circle-arrow-up,fa-book-copy,fa-book-font,fa-book-heart,fa-book-journal-whills,fa-journal-whills,fa-book-medical,fa-book-open,fa-book-open-alt,fa-book-open-cover,fa-book-open-reader,fa-book-reader,fa-book-quran,fa-quran,fa-book-law,fa-book-section,fa-book-dead,fa-book-skull,fa-book-sparkles,fa-book-spells,fa-book-tanakh,fa-tanakh,fa-book-user,fa-bookmark,fa-bookmark-slash,fa-books,fa-books-medical,fa-boombox,fa-boot,fa-booth-curtain,fa-border-all,fa-border-bottom,fa-border-bottom-right,fa-border-style-alt,fa-border-center-h,fa-border-center-v,fa-border-inner,fa-border-left,fa-border-none,fa-border-outer,fa-border-right,fa-border-top,fa-border-style,fa-border-top-left,fa-bow-arrow,fa-bowl-chopsticks,fa-bowl-chopsticks-noodles,fa-bowl-hot,fa-soup,fa-bowl-rice,fa-bowling-ball,fa-bowling-ball-pin,fa-bowling-pins,fa-box,fa-archive,fa-box-archive,fa-box-ballot,fa-box-check,fa-box-circle-check,fa-box-dollar,fa-box-usd,fa-box-heart,fa-box-open,fa-box-full,fa-box-open-full,fa-box-alt,fa-box-taped,fa-box-tissue,fa-boxes-alt,fa-boxes-stacked,fa-boxes,fa-boxing-glove,fa-glove-boxing,fa-bracket-curly-left,fa-bracket-curly,fa-bracket-curly-right,fa-bracket-round,fa-parenthesis,fa-bracket-round-right,fa-bracket-left,fa-bracket-square,fa-bracket,fa-bracket-square-right,fa-brackets-curly,fa-brackets-round,fa-parentheses,fa-brackets-square,fa-brackets,fa-braille,fa-brain,fa-brain-arrow-curved-right,fa-mind-share,fa-brain-circuit,fa-brake-warning,fa-bread-loaf,fa-bread-slice,fa-briefcase,fa-briefcase-arrow-right,fa-briefcase-blank,fa-briefcase-clock,fa-business-time,fa-briefcase-medical,fa-brightness,fa-brightness-low,fa-bring-forward,fa-bring-front,fa-broom,fa-browser,fa-browsers,fa-brush,fa-bug,fa-building,fa-buildings,fa-bullhorn,fa-bullseye,fa-bullseye-arrow,fa-bullseye-pointer,fa-burger,fa-hamburger,fa-burger-cheese,fa-cheeseburger,fa-burger-fries,fa-burger-glass,fa-burger-soda,fa-burrito,fa-bus,fa-bus-school,fa-bus-alt,fa-bus-simple,fa-c,fa-cabinet-filing,fa-cable-car,fa-cactus,fa-birthday-cake,fa-cake-candles,fa-calculator,fa-calculator-alt,fa-calculator-simple,fa-calendar,fa-calendar-arrow-down,fa-calendar-download,fa-calendar-arrow-up,fa-calendar-upload,fa-calendar-check,fa-calendar-clock,fa-calendar-time,fa-calendar-day,fa-calendar-alt,fa-calendar-days,fa-calendar-exclamation,fa-calendar-heart,fa-calendar-image,fa-calendar-lines,fa-calendar-note,fa-calendar-minus,fa-calendar-edit,fa-calendar-pen,fa-calendar-plus,fa-calendar-range,fa-calendar-star,fa-calendar-week,fa-calendar-times,fa-calendar-xmark,fa-calendars,fa-camcorder,fa-video-handheld,fa-camera-alt,fa-camera,fa-camera-cctv,fa-cctv,fa-camera-movie,fa-camera-polaroid,fa-camera-retro,fa-camera-rotate,fa-camera-home,fa-camera-security,fa-camera-slash,fa-camera-viewfinder,fa-camera-web,fa-webcam,fa-camera-web-slash,fa-webcam-slash,fa-campfire,fa-campground,fa-candle-holder,fa-candy-cane,fa-candy-corn,fa-cannabis,fa-capsules,fa-automobile,fa-car,fa-battery-car,fa-car-battery,fa-car-building,fa-car-bump,fa-car-bus,fa-car-crash,fa-car-garage,fa-car-alt,fa-car-rear,fa-car-side,fa-car-tilt,fa-car-wash,fa-car-mechanic,fa-car-wrench,fa-caravan,fa-caravan-alt,fa-caravan-simple,fa-caret-down,fa-caret-left,fa-caret-right,fa-caret-up,fa-carrot,fa-cars,fa-cart-arrow-down,fa-cart-flatbed,fa-dolly-flatbed,fa-cart-flatbed-boxes,fa-dolly-flatbed-alt,fa-cart-flatbed-empty,fa-dolly-flatbed-empty,fa-cart-flatbed-suitcase,fa-luggage-cart,fa-cart-minus,fa-cart-plus,fa-cart-shopping,fa-shopping-cart,fa-cart-shopping-fast,fa-cart-xmark,fa-cash-register,fa-betamax,fa-cassette-betamax,fa-cassette-tape,fa-cassette-vhs,fa-vhs,fa-castle,fa-cat,fa-cat-space,fa-cauldron,fa-cedi-sign,fa-cent-sign,fa-certificate,fa-chair,fa-chair-office,fa-blackboard,fa-chalkboard,fa-chalkboard-teacher,fa-chalkboard-user,fa-champagne-glass,fa-glass-champagne,fa-champagne-glasses,fa-glass-cheers,fa-charging-station,fa-area-chart,fa-chart-area,fa-bar-chart,fa-chart-bar,fa-chart-bullet,fa-chart-candlestick,fa-chart-column,fa-chart-gantt,fa-chart-line,fa-line-chart,fa-chart-line-down,fa-chart-line-up,fa-analytics,fa-chart-mixed,fa-chart-network,fa-chart-pie,fa-pie-chart,fa-chart-pie-alt,fa-chart-pie-simple,fa-chart-pyramid,fa-chart-radar,fa-chart-scatter,fa-chart-scatter-3d,fa-chart-scatter-bubble,fa-chart-tree-map,fa-chart-user,fa-user-chart,fa-chart-waterfall,fa-check,fa-check-double,fa-check-to-slot,fa-vote-yea,fa-cheese,fa-cheese-swiss,fa-cherries,fa-chess,fa-chess-bishop,fa-chess-bishop-alt,fa-chess-bishop-piece,fa-chess-board,fa-chess-clock,fa-chess-clock-alt,fa-chess-clock-flip,fa-chess-king,fa-chess-king-alt,fa-chess-king-piece,fa-chess-knight,fa-chess-knight-alt,fa-chess-knight-piece,fa-chess-pawn,fa-chess-pawn-alt,fa-chess-pawn-piece,fa-chess-queen,fa-chess-queen-alt,fa-chess-queen-piece,fa-chess-rook,fa-chess-rook-alt,fa-chess-rook-piece,fa-chevron-down,fa-chevron-left,fa-chevron-right,fa-chevron-up,fa-chevron-double-down,fa-chevrons-down,fa-chevron-double-left,fa-chevrons-left,fa-chevron-double-right,fa-chevrons-right,fa-chevron-double-up,fa-chevrons-up,fa-child,fa-chimney,fa-church,fa-circle,fa-circle-0,fa-circle-1,fa-circle-2,fa-circle-3,fa-circle-4,fa-circle-5,fa-circle-6,fa-circle-7,fa-circle-8,fa-circle-9,fa-circle-a,fa-circle-ampersand,fa-arrow-circle-down,fa-circle-arrow-down,fa-circle-arrow-down-left,fa-circle-arrow-down-right,fa-arrow-circle-left,fa-circle-arrow-left,fa-arrow-circle-right,fa-circle-arrow-right,fa-arrow-circle-up,fa-circle-arrow-up,fa-circle-arrow-up-left,fa-circle-arrow-up-right,fa-circle-b,fa-circle-bolt,fa-book-circle,fa-circle-book-open,fa-bookmark-circle,fa-circle-bookmark,fa-circle-c,fa-calendar-circle,fa-circle-calendar,fa-camera-circle,fa-circle-camera,fa-caret-circle-down,fa-circle-caret-down,fa-caret-circle-left,fa-circle-caret-left,fa-caret-circle-right,fa-circle-caret-right,fa-caret-circle-up,fa-circle-caret-up,fa-check-circle,fa-circle-check,fa-chevron-circle-down,fa-circle-chevron-down,fa-chevron-circle-left,fa-circle-chevron-left,fa-chevron-circle-right,fa-circle-chevron-right,fa-chevron-circle-up,fa-circle-chevron-up,fa-circle-d,fa-circle-dashed,fa-circle-divide,fa-circle-dollar,fa-dollar-circle,fa-usd-circle,fa-circle-dollar-to-slot,fa-donate,fa-circle-dot,fa-dot-circle,fa-arrow-alt-circle-down,fa-circle-down,fa-circle-down-left,fa-circle-down-right,fa-circle-e,fa-circle-ellipsis,fa-circle-ellipsis-vertical,fa-circle-envelope,fa-envelope-circle,fa-circle-exclamation,fa-exclamation-circle,fa-circle-exclamation-check,fa-circle-f,fa-circle-g,fa-circle-h,fa-hospital-symbol,fa-circle-half,fa-adjust,fa-circle-half-stroke,fa-circle-heart,fa-heart-circle,fa-circle-i,fa-circle-info,fa-info-circle,fa-circle-j,fa-circle-k,fa-circle-l,fa-arrow-alt-circle-left,fa-circle-left,fa-circle-location-arrow,fa-location-circle,fa-circle-m,fa-circle-microphone,fa-microphone-circle,fa-circle-microphone-lines,fa-microphone-circle-alt,fa-circle-minus,fa-minus-circle,fa-circle-n,fa-circle-notch,fa-circle-o,fa-circle-p,fa-circle-parking,fa-parking-circle,fa-circle-pause,fa-pause-circle,fa-circle-phone,fa-phone-circle,fa-circle-phone-flip,fa-phone-circle-alt,fa-circle-phone-hangup,fa-phone-circle-down,fa-circle-play,fa-play-circle,fa-circle-plus,fa-plus-circle,fa-circle-q,fa-circle-quarter,fa-circle-question,fa-question-circle,fa-circle-r,fa-circle-radiation,fa-radiation-alt,fa-arrow-alt-circle-right,fa-circle-right,fa-circle-s,fa-circle-small,fa-circle-sort,fa-sort-circle,fa-circle-sort-down,fa-sort-circle-down,fa-circle-sort-up,fa-sort-circle-up,fa-circle-star,fa-star-circle,fa-circle-stop,fa-stop-circle,fa-circle-t,fa-circle-three-quarters,fa-circle-trash,fa-trash-circle,fa-circle-u,fa-arrow-alt-circle-up,fa-circle-up,fa-circle-up-left,fa-circle-up-right,fa-circle-user,fa-user-circle,fa-circle-v,fa-circle-video,fa-video-circle,fa-circle-w,fa-circle-waveform-lines,fa-waveform-circle,fa-circle-x,fa-circle-xmark,fa-times-circle,fa-xmark-circle,fa-circle-y,fa-circle-z,fa-citrus,fa-citrus-slice,fa-city,fa-clapperboard,fa-clapperboard-play,fa-clarinet,fa-claw-marks,fa-clipboard,fa-clipboard-check,fa-clipboard-list,fa-clipboard-list-check,fa-clipboard-medical,fa-clipboard-prescription,fa-clipboard-user,fa-clock,fa-clock-desk,fa-clock-rotate-left,fa-history,fa-clone,fa-closed-captioning,fa-closed-captioning-slash,fa-clothes-hanger,fa-cloud,fa-cloud-arrow-down,fa-cloud-download-alt,fa-cloud-download,fa-cloud-arrow-up,fa-cloud-upload-alt,fa-cloud-upload,fa-cloud-bolt,fa-thunderstorm,fa-cloud-bolt-moon,fa-thunderstorm-moon,fa-cloud-bolt-sun,fa-thunderstorm-sun,fa-cloud-drizzle,fa-cloud-fog,fa-fog,fa-cloud-hail,fa-cloud-hail-mixed,fa-cloud-meatball,fa-cloud-moon,fa-cloud-moon-rain,fa-cloud-music,fa-cloud-rain,fa-cloud-rainbow,fa-cloud-showers,fa-cloud-showers-heavy,fa-cloud-slash,fa-cloud-sleet,fa-cloud-snow,fa-cloud-sun,fa-cloud-sun-rain,fa-cloud-word,fa-clouds,fa-clouds-moon,fa-clouds-sun,fa-clover,fa-club,fa-coconut,fa-code,fa-code-branch,fa-code-commit,fa-code-compare,fa-code-fork,fa-code-merge,fa-code-pull-request,fa-code-simple,fa-coffee-bean,fa-coffee-beans,fa-coffee-pot,fa-coffin,fa-coffin-cross,fa-coin,fa-coins,fa-colon,fa-colon-sign,fa-comet,fa-comma,fa-command,fa-comment,fa-comment-arrow-down,fa-comment-arrow-up,fa-comment-arrow-up-right,fa-comment-captions,fa-comment-check,fa-comment-code,fa-comment-dollar,fa-comment-dots,fa-commenting,fa-comment-exclamation,fa-comment-image,fa-comment-lines,fa-comment-medical,fa-comment-middle,fa-comment-middle-top,fa-comment-minus,fa-comment-music,fa-comment-edit,fa-comment-pen,fa-comment-plus,fa-comment-question,fa-comment-quote,fa-comment-slash,fa-comment-smile,fa-comment-sms,fa-sms,fa-comment-text,fa-comment-times,fa-comment-xmark,fa-comments,fa-comments-dollar,fa-comments-question,fa-comments-question-check,fa-compact-disc,fa-compass,fa-compass-drafting,fa-drafting-compass,fa-compass-slash,fa-compress,fa-compress-wide,fa-computer-classic,fa-computer-mouse,fa-mouse,fa-computer-mouse-scrollwheel,fa-mouse-alt,fa-computer-speaker,fa-container-storage,fa-conveyor-belt,fa-conveyor-belt-alt,fa-conveyor-belt-boxes,fa-conveyor-belt-empty,fa-cookie,fa-cookie-bite,fa-copy,fa-copyright,fa-corn,fa-corner,fa-couch,fa-cow,fa-cowbell,fa-cowbell-circle-plus,fa-cowbell-more,fa-crate-apple,fa-apple-crate,fa-crate-empty,fa-credit-card-alt,fa-credit-card,fa-credit-card-blank,fa-credit-card-front,fa-cricket-bat-ball,fa-cricket,fa-croissant,fa-crop,fa-crop-alt,fa-crop-simple,fa-cross,fa-crosshairs,fa-crow,fa-crown,fa-crutch,fa-crutches,fa-cruzeiro-sign,fa-cube,fa-cubes,fa-coffee-togo,fa-cup-togo,fa-curling-stone,fa-curling,fa-d,fa-dagger,fa-dash,fa-database,fa-deer,fa-deer-rudolph,fa-backspace,fa-delete-left,fa-delete-right,fa-democrat,fa-desktop-alt,fa-desktop,fa-desktop-arrow-down,fa-dharmachakra,fa-diagram-lean-canvas,fa-diagram-nested,fa-diagram-project,fa-project-diagram,fa-diagram-sankey,fa-diagram-venn,fa-dial-med-high,fa-dial,fa-dial-high,fa-dial-low,fa-dial-max,fa-dial-med,fa-dial-med-low,fa-dial-min,fa-dial-off,fa-diamond,fa-diamond-turn-right,fa-directions,fa-dice,fa-dice-d10,fa-dice-d12,fa-dice-d20,fa-dice-d4,fa-dice-d6,fa-dice-d8,fa-dice-five,fa-dice-four,fa-dice-one,fa-dice-six,fa-dice-three,fa-dice-two,fa-diploma,fa-scroll-ribbon,fa-disc-drive,fa-disease,fa-display,fa-display-arrow-down,fa-desktop-code,fa-display-code,fa-desktop-medical,fa-display-medical,fa-desktop-slash,fa-display-slash,fa-ditto,fa-divide,fa-dna,fa-do-not-enter,fa-dog,fa-dog-leashed,fa-dollar-sign,fa-dollar,fa-usd,fa-dolly-box,fa-dolly,fa-dolly-empty,fa-dolphin,fa-dong-sign,fa-door-closed,fa-door-open,fa-dove,fa-arrow-alt-down,fa-down,fa-arrow-alt-from-top,fa-down-from-line,fa-down-left,fa-compress-alt,fa-down-left-and-up-right-to-center,fa-down-long,fa-long-arrow-alt-down,fa-down-right,fa-arrow-alt-to-bottom,fa-down-to-line,fa-download,fa-dragon,fa-draw-circle,fa-draw-polygon,fa-draw-square,fa-dreidel,fa-drone,fa-drone-alt,fa-drone-front,fa-droplet,fa-tint,fa-dewpoint,fa-droplet-degree,fa-droplet-percent,fa-humidity,fa-droplet-slash,fa-tint-slash,fa-drum,fa-drum-steelpan,fa-drumstick,fa-drumstick-bite,fa-dryer,fa-dryer-alt,fa-dryer-heat,fa-duck,fa-dumbbell,fa-dumpster,fa-dumpster-fire,fa-dungeon,fa-e,fa-ear,fa-deaf,fa-deafness,fa-ear-deaf,fa-hard-of-hearing,fa-assistive-listening-systems,fa-ear-listen,fa-ear-muffs,fa-earth-africa,fa-globe-africa,fa-earth-americas,fa-earth,fa-globe-americas,fa-earth-asia,fa-globe-asia,fa-earth-europa,fa-globe-europe,fa-eclipse,fa-egg,fa-egg-fried,fa-eggplant,fa-eject,fa-elephant,fa-elevator,fa-ellipsis-h,fa-ellipsis,fa-ellipsis-h-alt,fa-ellipsis-stroke,fa-ellipsis-stroke-vertical,fa-ellipsis-v-alt,fa-ellipsis-v,fa-ellipsis-vertical,fa-empty-set,fa-engine,fa-engine-exclamation,fa-engine-warning,fa-envelope,fa-envelope-badge,fa-envelope-dot,fa-envelope-open,fa-envelope-open-dollar,fa-envelope-open-text,fa-envelopes,fa-envelopes-bulk,fa-mail-bulk,fa-equals,fa-eraser,fa-escalator,fa-ethernet,fa-eur,fa-euro-sign,fa-euro,fa-exclamation,fa-expand,fa-expand-wide,fa-eye,fa-eye-dropper-empty,fa-eye-dropper,fa-eyedropper,fa-eye-dropper-full,fa-eye-dropper-half,fa-eye-evil,fa-eye-low-vision,fa-low-vision,fa-eye-slash,fa-f,fa-angry,fa-face-angry,fa-dizzy,fa-face-dizzy,fa-exploding-head,fa-face-explode,fa-face-flushed,fa-flushed,fa-face-frown,fa-frown,fa-face-frown-open,fa-frown-open,fa-face-grimace,fa-grimace,fa-face-grin,fa-grin,fa-face-grin-beam,fa-grin-beam,fa-face-grin-beam-sweat,fa-grin-beam-sweat,fa-face-grin-hearts,fa-grin-hearts,fa-face-grin-squint,fa-grin-squint,fa-face-grin-squint-tears,fa-grin-squint-tears,fa-face-grin-stars,fa-grin-stars,fa-face-grin-tears,fa-grin-tears,fa-face-grin-tongue,fa-grin-tongue,fa-face-grin-tongue-squint,fa-grin-tongue-squint,fa-face-grin-tongue-wink,fa-grin-tongue-wink,fa-face-grin-wide,fa-grin-alt,fa-face-grin-wink,fa-grin-wink,fa-face-kiss,fa-kiss,fa-face-kiss-beam,fa-kiss-beam,fa-face-kiss-wink-heart,fa-kiss-wink-heart,fa-face-laugh,fa-laugh,fa-face-laugh-beam,fa-laugh-beam,fa-face-laugh-squint,fa-laugh-squint,fa-face-laugh-wink,fa-laugh-wink,fa-face-meh,fa-meh,fa-face-meh-blank,fa-meh-blank,fa-face-rolling-eyes,fa-meh-rolling-eyes,fa-face-sad-cry,fa-sad-cry,fa-face-sad-tear,fa-sad-tear,fa-face-smile,fa-smile,fa-face-smile-beam,fa-smile-beam,fa-face-smile-plus,fa-smile-plus,fa-face-smile-wink,fa-smile-wink,fa-face-surprise,fa-surprise,fa-face-tired,fa-tired,fa-face-viewfinder,fa-family,fa-family-dress,fa-family-pants,fa-fan,fa-fan-table,fa-barn-silo,fa-farm,fa-faucet,fa-faucet-drip,fa-fax,fa-feather,fa-feather-alt,fa-feather-pointed,fa-fence,fa-ferris-wheel,fa-field-hockey-stick-ball,fa-field-hockey,fa-file,fa-file-arrow-down,fa-file-download,fa-file-arrow-up,fa-file-upload,fa-file-audio,fa-file-binary,fa-file-award,fa-file-certificate,fa-file-chart-column,fa-file-chart-line,fa-file-chart-pie,fa-file-check,fa-file-code,fa-file-contract,fa-file-csv,fa-file-dashed-line,fa-page-break,fa-file-excel,fa-file-exclamation,fa-arrow-right-from-file,fa-file-export,fa-file-heart,fa-file-image,fa-arrow-right-to-file,fa-file-import,fa-file-invoice,fa-file-invoice-dollar,fa-file-alt,fa-file-lines,fa-file-text,fa-file-magnifying-glass,fa-file-search,fa-file-medical,fa-file-minus,fa-file-music,fa-file-pdf,fa-file-edit,fa-file-pen,fa-file-plus,fa-file-plus-minus,fa-file-powerpoint,fa-file-prescription,fa-file-signature,fa-file-spreadsheet,fa-file-user,fa-file-video,fa-file-medical-alt,fa-file-waveform,fa-file-word,fa-file-times,fa-file-xmark,fa-file-archive,fa-file-zipper,fa-files,fa-files-medical,fa-fill,fa-fill-drip,fa-film,fa-film-canister,fa-film-alt,fa-film-simple,fa-film-slash,fa-films,fa-filter,fa-filter-circle-dollar,fa-funnel-dollar,fa-filter-circle-xmark,fa-filter-list,fa-filter-slash,fa-filters,fa-fingerprint,fa-fire,fa-fire-extinguisher,fa-fire-flame,fa-flame,fa-fire-alt,fa-fire-flame-curved,fa-burn,fa-fire-flame-simple,fa-fire-hydrant,fa-fire-smoke,fa-fireplace,fa-fish,fa-fish-bones,fa-fish-cooked,fa-flag,fa-flag-checkered,fa-flag-pennant,fa-pennant,fa-flag-alt,fa-flag-swallowtail,fa-flag-usa,fa-flashlight,fa-flask,fa-flask-poison,fa-flask-round-poison,fa-flask-potion,fa-flask-round-potion,fa-floppy-disk,fa-save,fa-floppy-disk-circle-arrow-right,fa-save-circle-arrow-right,fa-floppy-disk-circle-xmark,fa-floppy-disk-times,fa-save-circle-xmark,fa-save-times,fa-floppy-disk-pen,fa-floppy-disks,fa-florin-sign,fa-flower,fa-flower-daffodil,fa-flower-tulip,fa-flute,fa-flux-capacitor,fa-folder,fa-folder-arrow-down,fa-folder-download,fa-folder-arrow-up,fa-folder-upload,fa-folder-blank,fa-folder-bookmark,fa-folder-cog,fa-folder-gear,fa-folder-grid,fa-folder-heart,fa-folder-image,fa-folder-magnifying-glass,fa-folder-search,fa-folder-medical,fa-folder-minus,fa-folder-music,fa-folder-open,fa-folder-plus,fa-folder-tree,fa-folder-user,fa-folder-times,fa-folder-xmark,fa-folders,fa-font,fa-font-case,fa-football-ball,fa-football-helmet,fa-fork,fa-utensil-fork,fa-fork-knife,fa-utensils-alt,fa-forklift,fa-forward,fa-fast-forward,fa-forward-fast,fa-forward-step,fa-step-forward,fa-franc-sign,fa-french-fries,fa-frog,fa-function,fa-futbol-ball,fa-futbol,fa-soccer-ball,fa-g,fa-galaxy,fa-game-board,fa-game-board-alt,fa-game-board-simple,fa-game-console-handheld,fa-gamepad,fa-gamepad-alt,fa-gamepad-modern,fa-garage,fa-garage-car,fa-garage-open,fa-gas-pump,fa-gas-pump-slash,fa-dashboard,fa-gauge-high,fa-gauge,fa-tachometer-alt-fast,fa-tachometer-alt,fa-gauge-low,fa-tachometer-alt-slow,fa-gauge-max,fa-tachometer-alt-fastest,fa-gauge-med,fa-tachometer-alt-average,fa-gauge-min,fa-tachometer-alt-slowest,fa-gauge-simple-high,fa-gauge-simple,fa-tachometer,fa-gauge-simple-low,fa-tachometer-slow,fa-gauge-simple-max,fa-tachometer-fastest,fa-gauge-simple-med,fa-tachometer-average,fa-gauge-simple-min,fa-tachometer-slowest,fa-gavel,fa-legal,fa-cog,fa-gear,fa-cogs,fa-gears,fa-gem,fa-genderless,fa-ghost,fa-gif,fa-gift,fa-gift-card,fa-gifts,fa-gingerbread-man,fa-glass,fa-glass-citrus,fa-glass-empty,fa-glass-half-empty,fa-glass-half-full,fa-glass-half,fa-glasses,fa-glasses-alt,fa-glasses-round,fa-globe,fa-globe-snow,fa-globe-stand,fa-golf-ball-tee,fa-golf-ball,fa-golf-club,fa-gopuram,fa-graduation-cap,fa-mortar-board,fa-gramophone,fa-grapes,fa-grate,fa-grate-droplet,fa-greater-than,fa-greater-than-equal,fa-grid-3,fa-grid,fa-grid-2,fa-grid-2-plus,fa-grid-4,fa-grid-5,fa-grid-horizontal,fa-grip-horizontal,fa-grip,fa-grip-lines,fa-grip-lines-vertical,fa-grip-vertical,fa-guarani-sign,fa-guitar,fa-guitar-electric,fa-guitars,fa-gun,fa-gun-slash,fa-gun-squirt,fa-h,fa-h1,fa-h2,fa-h3,fa-h4,fa-hammer,fa-hammer-war,fa-hamsa,fa-hand-back-point-down,fa-hand-back-point-left,fa-hand-back-point-ribbon,fa-hand-back-point-right,fa-hand-back-point-up,fa-allergies,fa-hand-dots,fa-hand-fingers-crossed,fa-fist-raised,fa-hand-fist,fa-hand-heart,fa-hand-holding,fa-hand-holding-box,fa-hand-holding-dollar,fa-hand-holding-usd,fa-hand-holding-droplet,fa-hand-holding-water,fa-hand-holding-heart,fa-hand-holding-magic,fa-hand-holding-medical,fa-hand-holding-seedling,fa-hand-holding-skull,fa-hand-horns,fa-hand-lizard,fa-hand-love,fa-hand-middle-finger,fa-hand-paper,fa-hand-peace,fa-hand-point-down,fa-hand-point-left,fa-hand-point-ribbon,fa-hand-point-right,fa-hand-point-up,fa-hand-pointer,fa-hand-rock,fa-hand-scissors,fa-hand-sparkles,fa-hand-spock,fa-hand-wave,fa-hands,fa-sign-language,fa-signing,fa-american-sign-language-interpreting,fa-asl-interpreting,fa-hands-american-sign-language-interpreting,fa-hands-asl-interpreting,fa-hands-bubbles,fa-hands-wash,fa-hands-clapping,fa-hands-holding,fa-hand-receiving,fa-hands-holding-diamond,fa-hands-holding-dollar,fa-hands-usd,fa-hands-heart,fa-hands-holding-heart,fa-hands-praying,fa-praying-hands,fa-handshake,fa-hands-helping,fa-handshake-angle,fa-handshake-alt,fa-handshake-simple,fa-handshake-alt-slash,fa-handshake-simple-slash,fa-handshake-slash,fa-hanukiah,fa-hard-drive,fa-hdd,fa-hashtag,fa-hat-chef,fa-hat-cowboy,fa-hat-cowboy-side,fa-hat-santa,fa-hat-winter,fa-hat-witch,fa-hat-wizard,fa-head-side,fa-head-side-brain,fa-head-side-cough,fa-head-side-cough-slash,fa-head-side-goggles,fa-head-vr,fa-head-side-headphones,fa-head-side-heart,fa-head-side-mask,fa-head-side-medical,fa-head-side-virus,fa-header,fa-heading,fa-headphones,fa-headphones-alt,fa-headphones-simple,fa-headset,fa-heart,fa-heart-broken,fa-heart-crack,fa-heart-half,fa-heart-half-alt,fa-heart-half-stroke,fa-heart-pulse,fa-heartbeat,fa-heat,fa-helicopter,fa-helmet-battle,fa-hard-hat,fa-hat-hard,fa-helmet-safety,fa-hexagon,fa-hexagon-divide,fa-hexagon-minus,fa-minus-hexagon,fa-hexagon-plus,fa-plus-hexagon,fa-hexagon-xmark,fa-times-hexagon,fa-xmark-hexagon,fa-high-definition,fa-rectangle-hd,fa-highlighter,fa-highlighter-line,fa-hippo,fa-hockey-mask,fa-hockey-puck,fa-hockey-sticks,fa-holly-berry,fa-home-lg,fa-home,fa-home-blank,fa-home-lg-alt,fa-home-simple,fa-home-heart,fa-home-user,fa-hood-cloak,fa-horizontal-rule,fa-horse,fa-horse-head,fa-horse-saddle,fa-hospital,fa-hospital-user,fa-hospital-alt,fa-hospital-wide,fa-hospitals,fa-hot-tub-person,fa-hot-tub,fa-hotdog,fa-hotel,fa-hourglass-2,fa-hourglass-half,fa-hourglass,fa-hourglass-empty,fa-hourglass-3,fa-hourglass-end,fa-hourglass-1,fa-hourglass-start,fa-house,fa-house-building,fa-house-crack,fa-house-damage,fa-house-day,fa-house-flood,fa-house-heart,fa-house-laptop,fa-laptop-house,fa-clinic-medical,fa-house-medical,fa-house-night,fa-house-person-depart,fa-house-person-leave,fa-house-person-arrive,fa-house-person-return,fa-house-signal,fa-house-tree,fa-house-turret,fa-house-user,fa-hryvnia-sign,fa-hryvnia,fa-hurricane,fa-i,fa-i-cursor,fa-ice-cream,fa-ice-skate,fa-icicles,fa-heart-music-camera-bolt,fa-icons,fa-id-badge,fa-drivers-license,fa-id-card,fa-id-card-alt,fa-id-card-clip,fa-igloo,fa-image,fa-image-landscape,fa-landscape,fa-image-polaroid,fa-image-polaroid-user,fa-image-portrait,fa-portrait,fa-image-slash,fa-image-user,fa-images,fa-images-user,fa-inbox,fa-inbox-full,fa-inbox-arrow-down,fa-inbox-in,fa-inbox-arrow-up,fa-inbox-out,fa-inboxes,fa-indent,fa-indian-rupee-sign,fa-indian-rupee,fa-inr,fa-industry,fa-industry-alt,fa-industry-windows,fa-infinity,fa-info,fa-inhaler,fa-input-numeric,fa-input-pipe,fa-input-text,fa-integral,fa-intersection,fa-island-tree-palm,fa-island-tropical,fa-italic,fa-j,fa-jack-o-lantern,fa-jedi,fa-fighter-jet,fa-jet-fighter,fa-joint,fa-joystick,fa-jug,fa-k,fa-kaaba,fa-kazoo,fa-kerning,fa-key,fa-key-skeleton,fa-keyboard,fa-keyboard-brightness,fa-keyboard-brightness-low,fa-keyboard-down,fa-keyboard-left,fa-keynote,fa-khanda,fa-kidneys,fa-kip-sign,fa-first-aid,fa-kit-medical,fa-kite,fa-kiwi-bird,fa-kiwi-fruit,fa-knife,fa-utensil-knife,fa-knife-kitchen,fa-l,fa-lambda,fa-lamp,fa-lamp-desk,fa-lamp-floor,fa-lamp-street,fa-landmark,fa-landmark-alt,fa-landmark-dome,fa-language,fa-laptop,fa-laptop-arrow-down,fa-laptop-code,fa-laptop-medical,fa-laptop-mobile,fa-phone-laptop,fa-laptop-slash,fa-lari-sign,fa-lasso,fa-lasso-sparkles,fa-layer-group,fa-layer-group-minus,fa-layer-minus,fa-layer-group-plus,fa-layer-plus,fa-leaf,fa-leaf-heart,fa-leaf-maple,fa-leaf-oak,fa-arrow-alt-left,fa-left,fa-arrow-alt-from-right,fa-left-from-line,fa-left-long,fa-long-arrow-alt-left,fa-arrows-alt-h,fa-left-right,fa-arrow-alt-to-left,fa-left-to-line,fa-lemon,fa-less-than,fa-less-than-equal,fa-life-ring,fa-light-ceiling,fa-light-switch,fa-light-switch-off,fa-light-switch-on,fa-lightbulb,fa-lightbulb-dollar,fa-lightbulb-exclamation,fa-lightbulb-exclamation-on,fa-lightbulb-on,fa-lightbulb-slash,fa-lights-holiday,fa-line-columns,fa-line-height,fa-chain,fa-link,fa-chain-horizontal,fa-link-horizontal,fa-chain-horizontal-slash,fa-link-horizontal-slash,fa-link-simple,fa-link-simple-slash,fa-chain-broken,fa-chain-slash,fa-link-slash,fa-unlink,fa-lips,fa-lira-sign,fa-list-squares,fa-list,fa-list-check,fa-tasks,fa-list-dropdown,fa-list-music,fa-list-1-2,fa-list-numeric,fa-list-ol,fa-list-radio,fa-list-timeline,fa-list-tree,fa-list-dots,fa-list-ul,fa-litecoin-sign,fa-loader,fa-location,fa-map-marker,fa-location-arrow,fa-location-check,fa-map-marker-check,fa-location-crosshairs,fa-location-crosshairs-slash,fa-location-dot,fa-map-marker-alt,fa-location-dot-slash,fa-map-marker-alt-slash,fa-location-exclamation,fa-map-marker-exclamation,fa-location-minus,fa-map-marker-minus,fa-location-pen,fa-map-marker-edit,fa-location-plus,fa-map-marker-plus,fa-location-question,fa-map-marker-question,fa-location-slash,fa-map-marker-slash,fa-location-smile,fa-map-marker-smile,fa-location-xmark,fa-map-marker-times,fa-map-marker-xmark,fa-lock,fa-lock-alt,fa-lock-keyhole,fa-lock-keyhole-open,fa-lock-open-alt,fa-lock-open,fa-couch-small,fa-loveseat,fa-luchador-mask,fa-luchador,fa-mask-luchador,fa-lungs,fa-lungs-virus,fa-m,fa-mace,fa-magnet,fa-magnifying-glass,fa-search,fa-magnifying-glass-dollar,fa-search-dollar,fa-magnifying-glass-location,fa-search-location,fa-magnifying-glass-minus,fa-search-minus,fa-magnifying-glass-plus,fa-search-plus,fa-mailbox,fa-manat-sign,fa-mandolin,fa-mango,fa-manhole,fa-map,fa-map-location,fa-map-marked,fa-map-location-dot,fa-map-marked-alt,fa-map-pin,fa-marker,fa-mars,fa-mars-double,fa-mars-stroke,fa-mars-stroke-h,fa-mars-stroke-right,fa-mars-stroke-up,fa-mars-stroke-v,fa-glass-martini-alt,fa-martini-glass,fa-cocktail,fa-martini-glass-citrus,fa-glass-martini,fa-martini-glass-empty,fa-mask,fa-mask-face,fa-masks-theater,fa-theater-masks,fa-expand-arrows-alt,fa-maximize,fa-meat,fa-medal,fa-megaphone,fa-melon,fa-melon-slice,fa-memo,fa-memo-circle-check,fa-memo-pad,fa-memory,fa-menorah,fa-mercury,fa-comment-alt,fa-message,fa-comment-alt-arrow-down,fa-message-arrow-down,fa-comment-alt-arrow-up,fa-message-arrow-up,fa-message-arrow-up-right,fa-comment-alt-captions,fa-message-captions,fa-comment-alt-check,fa-message-check,fa-message-code,fa-comment-alt-dollar,fa-message-dollar,fa-comment-alt-dots,fa-message-dots,fa-messaging,fa-comment-alt-exclamation,fa-message-exclamation,fa-comment-alt-image,fa-message-image,fa-comment-alt-lines,fa-message-lines,fa-comment-alt-medical,fa-message-medical,fa-comment-middle-alt,fa-message-middle,fa-comment-middle-top-alt,fa-message-middle-top,fa-comment-alt-minus,fa-message-minus,fa-comment-alt-music,fa-message-music,fa-comment-alt-edit,fa-message-edit,fa-message-pen,fa-comment-alt-plus,fa-message-plus,fa-message-question,fa-comment-alt-quote,fa-message-quote,fa-comment-alt-slash,fa-message-slash,fa-comment-alt-smile,fa-message-smile,fa-message-sms,fa-comment-alt-text,fa-message-text,fa-comment-alt-times,fa-message-times,fa-message-xmark,fa-comments-alt,fa-messages,fa-comments-alt-dollar,fa-messages-dollar,fa-messages-question,fa-meteor,fa-meter,fa-meter-bolt,fa-meter-droplet,fa-meter-fire,fa-microchip,fa-microchip-ai,fa-microphone,fa-microphone-alt,fa-microphone-lines,fa-microphone-alt-slash,fa-microphone-lines-slash,fa-microphone-slash,fa-microphone-stand,fa-microscope,fa-microwave,fa-mill-sign,fa-compress-arrows-alt,fa-minimize,fa-minus,fa-subtract,fa-mistletoe,fa-mitten,fa-mobile-android,fa-mobile-phone,fa-mobile,fa-mobile-button,fa-mobile-iphone,fa-mobile-notch,fa-mobile-android-alt,fa-mobile-screen,fa-mobile-alt,fa-mobile-screen-button,fa-mobile-signal,fa-mobile-signal-out,fa-money-bill,fa-money-bill-1,fa-money-bill-alt,fa-money-bill-1-wave,fa-money-bill-wave-alt,fa-money-bill-simple,fa-money-bill-simple-wave,fa-money-bill-wave,fa-money-bills,fa-money-bills-alt,fa-money-bills-simple,fa-money-check,fa-money-check-alt,fa-money-check-dollar,fa-money-check-dollar-pen,fa-money-check-edit-alt,fa-money-check-edit,fa-money-check-pen,fa-money-from-bracket,fa-money-simple-from-bracket,fa-monitor-heart-rate,fa-monitor-waveform,fa-monkey,fa-monument,fa-moon,fa-moon-cloud,fa-eclipse-alt,fa-moon-over-sun,fa-moon-stars,fa-mortar-pestle,fa-mosque,fa-motorcycle,fa-mountain,fa-mountains,fa-mp3-player,fa-mug,fa-mug-hot,fa-mug-marshmallows,fa-coffee,fa-mug-saucer,fa-mug-tea,fa-mug-tea-saucer,fa-music,fa-music-alt,fa-music-note,fa-music-alt-slash,fa-music-note-slash,fa-music-slash,fa-n,fa-naira-sign,fa-narwhal,fa-network-wired,fa-neuter,fa-newspaper,fa-nfc,fa-nfc-lock,fa-nfc-magnifying-glass,fa-nfc-pen,fa-nfc-signal,fa-nfc-slash,fa-nfc-trash,fa-not-equal,fa-notdef,fa-note,fa-note-medical,fa-note-sticky,fa-sticky-note,fa-notebook,fa-notes,fa-notes-medical,fa-o,fa-object-group,fa-object-ungroup,fa-octagon,fa-octagon-divide,fa-octagon-exclamation,fa-minus-octagon,fa-octagon-minus,fa-octagon-plus,fa-plus-octagon,fa-octagon-xmark,fa-times-octagon,fa-xmark-octagon,fa-oil-can,fa-oil-can-drip,fa-oil-temp,fa-oil-temperature,fa-olive,fa-olive-branch,fa-om,fa-omega,fa-option,fa-ornament,fa-otter,fa-dedent,fa-outdent,fa-outlet,fa-oven,fa-overline,fa-p,fa-pager,fa-paint-brush,fa-paint-brush-alt,fa-paint-brush-fine,fa-paint-roller,fa-paintbrush-pencil,fa-palette,fa-pallet,fa-pallet-box,fa-palette-boxes,fa-pallet-alt,fa-pallet-boxes,fa-panorama,fa-paper-plane,fa-paper-plane-alt,fa-paper-plane-top,fa-send,fa-paperclip,fa-parachute-box,fa-paragraph,fa-paragraph-left,fa-paragraph-rtl,fa-party-bell,fa-party-horn,fa-passport,fa-file-clipboard,fa-paste,fa-pause,fa-paw,fa-paw-claws,fa-paw-alt,fa-paw-simple,fa-peace,fa-peach,fa-peapod,fa-pear,fa-pedestal,fa-pegasus,fa-pen,fa-pen-circle,fa-pen-alt,fa-pen-clip,fa-pen-alt-slash,fa-pen-clip-slash,fa-pen-fancy,fa-pen-fancy-slash,fa-pen-field,fa-pen-line,fa-pen-nib,fa-pen-paintbrush,fa-pencil-paintbrush,fa-pen-ruler,fa-pencil-ruler,fa-pen-slash,fa-pen-swirl,fa-edit,fa-pen-to-square,fa-pencil-alt,fa-pencil,fa-pencil-slash,fa-people,fa-people-arrows-left-right,fa-people-arrows,fa-people-carry-box,fa-people-carry,fa-people-dress,fa-people-dress-simple,fa-people-pants,fa-people-pants-simple,fa-people-simple,fa-pepper-hot,fa-percent,fa-percentage,fa-period,fa-male,fa-person,fa-biking,fa-person-biking,fa-biking-mountain,fa-person-biking-mountain,fa-person-booth,fa-person-carry-box,fa-person-carry,fa-digging,fa-person-digging,fa-person-dolly,fa-person-dolly-empty,fa-diagnoses,fa-person-dots-from-line,fa-female,fa-person-dress,fa-person-dress-simple,fa-person-from-portal,fa-portal-exit,fa-hiking,fa-person-hiking,fa-person-pinball,fa-person-praying,fa-pray,fa-person-pregnant,fa-person-running,fa-running,fa-person-seat,fa-person-seat-reclined,fa-person-sign,fa-person-simple,fa-person-skating,fa-skating,fa-person-ski-jumping,fa-ski-jump,fa-person-ski-lift,fa-ski-lift,fa-person-skiing,fa-skiing,fa-person-skiing-nordic,fa-skiing-nordic,fa-person-sledding,fa-sledding,fa-person-snowboarding,fa-snowboarding,fa-person-snowmobiling,fa-snowmobile,fa-person-swimming,fa-swimmer,fa-person-to-portal,fa-portal-enter,fa-person-walking,fa-walking,fa-blind,fa-person-walking-with-cane,fa-peseta-sign,fa-peso-sign,fa-phone,fa-phone-arrow-down-left,fa-phone-arrow-down,fa-phone-incoming,fa-phone-arrow-up-right,fa-phone-arrow-up,fa-phone-outgoing,fa-phone-alt,fa-phone-flip,fa-phone-hangup,fa-phone-missed,fa-phone-office,fa-phone-plus,fa-phone-rotary,fa-phone-slash,fa-phone-volume,fa-volume-control-phone,fa-phone-xmark,fa-photo-film,fa-photo-video,fa-photo-film-music,fa-pi,fa-piano,fa-piano-keyboard,fa-pie,fa-pig,fa-piggy-bank,fa-pills,fa-pinball,fa-pineapple,fa-pipe,fa-pizza,fa-pizza-slice,fa-place-of-worship,fa-plane,fa-plane-arrival,fa-plane-departure,fa-plane-alt,fa-plane-engines,fa-plane-prop,fa-plane-slash,fa-plane-tail,fa-plane-up,fa-plane-up-slash,fa-planet-moon,fa-planet-ringed,fa-play,fa-play-pause,fa-plug,fa-add,fa-plus,fa-plus-minus,fa-podcast,fa-podium,fa-podium-star,fa-police-box,fa-poll-people,fa-poo,fa-poo-bolt,fa-poo-storm,fa-poop,fa-popcorn,fa-power-off,fa-prescription,fa-prescription-bottle,fa-prescription-bottle-alt,fa-prescription-bottle-medical,fa-presentation-screen,fa-presentation,fa-print,fa-print-magnifying-glass,fa-print-search,fa-print-slash,fa-projector,fa-pump-medical,fa-pump-soap,fa-pumpkin,fa-puzzle-piece,fa-puzzle-piece-alt,fa-puzzle-piece-simple,fa-q,fa-qrcode,fa-question,fa-broom-ball,fa-quidditch-broom-ball,fa-quidditch,fa-quote-left-alt,fa-quote-left,fa-quote-right-alt,fa-quote-right,fa-quotes,fa-r,fa-rabbit,fa-rabbit-fast,fa-rabbit-running,fa-racquet,fa-radar,fa-radiation,fa-radio,fa-radio-alt,fa-radio-tuner,fa-rainbow,fa-raindrops,fa-ram,fa-ramp-loading,fa-raygun,fa-receipt,fa-record-vinyl,fa-rectangle-landscape,fa-rectangle,fa-ad,fa-rectangle-ad,fa-barcode-alt,fa-rectangle-barcode,fa-rectangle-code,fa-list-alt,fa-rectangle-list,fa-pro,fa-rectangle-pro,fa-rectangle-terminal,fa-rectangle-portrait,fa-rectangle-vertical,fa-rectangle-vertical-history,fa-rectangle-wide,fa-rectangle-times,fa-rectangle-xmark,fa-times-rectangle,fa-window-close,fa-rectangles-mixed,fa-recycle,fa-reel,fa-refrigerator,fa-registered,fa-repeat,fa-repeat-1,fa-mail-reply,fa-reply,fa-mail-reply-all,fa-reply-all,fa-reply-clock,fa-reply-time,fa-republican,fa-restroom,fa-restroom-simple,fa-retweet,fa-rhombus,fa-ribbon,fa-arrow-alt-right,fa-right,fa-right-from-bracket,fa-sign-out-alt,fa-arrow-alt-from-left,fa-right-from-line,fa-exchange-alt,fa-right-left,fa-long-arrow-alt-right,fa-right-long,fa-right-to-bracket,fa-sign-in-alt,fa-arrow-alt-to-right,fa-right-to-line,fa-ring,fa-rings-wedding,fa-road,fa-robot,fa-rocket,fa-rocket-launch,fa-roller-coaster,fa-rotate,fa-sync-alt,fa-rotate-exclamation,fa-rotate-back,fa-rotate-backward,fa-rotate-left,fa-undo-alt,fa-redo-alt,fa-rotate-forward,fa-rotate-right,fa-route,fa-route-highway,fa-route-interstate,fa-router,fa-feed,fa-rss,fa-rouble,fa-rub,fa-ruble-sign,fa-ruble,fa-ruler,fa-ruler-combined,fa-ruler-horizontal,fa-ruler-triangle,fa-ruler-vertical,fa-rupee-sign,fa-rupee,fa-rupiah-sign,fa-rv,fa-s,fa-sack,fa-sack-dollar,fa-bowl-salad,fa-salad,fa-sandwich,fa-satellite,fa-satellite-dish,fa-sausage,fa-saxophone,fa-sax-hot,fa-saxophone-fire,fa-balance-scale,fa-scale-balanced,fa-balance-scale-left,fa-scale-unbalanced,fa-balance-scale-right,fa-scale-unbalanced-flip,fa-scalpel,fa-scalpel-line-dashed,fa-scalpel-path,fa-scanner-image,fa-scanner,fa-scanner-gun,fa-scanner-keyboard,fa-scanner-touchscreen,fa-scarecrow,fa-scarf,fa-school,fa-cut,fa-scissors,fa-screen-users,fa-users-class,fa-screencast,fa-screwdriver,fa-screwdriver-wrench,fa-tools,fa-scribble,fa-scroll,fa-scroll-old,fa-scroll-torah,fa-torah,fa-scrubber,fa-scythe,fa-sd-card,fa-sd-cards,fa-seal,fa-seal-exclamation,fa-seal-question,fa-seat-airline,fa-section,fa-seedling,fa-sprout,fa-semicolon,fa-send-back,fa-send-backward,fa-sensor,fa-sensor-cloud,fa-sensor-smoke,fa-sensor-fire,fa-sensor-on,fa-sensor-alert,fa-sensor-triangle-exclamation,fa-server,fa-shapes,fa-triangle-circle-square,fa-arrow-turn-right,fa-mail-forward,fa-share,fa-arrows-turn-right,fa-share-all,fa-share-from-square,fa-share-square,fa-share-alt,fa-share-nodes,fa-sheep,fa-ils,fa-shekel-sign,fa-shekel,fa-sheqel-sign,fa-sheqel,fa-inventory,fa-shelves,fa-shelves-empty,fa-shield,fa-shield-alt,fa-shield-blank,fa-shield-check,fa-shield-cross,fa-shield-exclamation,fa-shield-keyhole,fa-shield-minus,fa-shield-plus,fa-shield-slash,fa-shield-virus,fa-shield-times,fa-shield-xmark,fa-ship,fa-shish-kebab,fa-shoe-prints,fa-shop,fa-store-alt,fa-shop-slash,fa-store-alt-slash,fa-shovel,fa-shovel-snow,fa-shower,fa-shower-alt,fa-shower-down,fa-shredder,fa-random,fa-shuffle,fa-shuttle-space,fa-space-shuttle,fa-shuttlecock,fa-sickle,fa-sidebar,fa-sidebar-flip,fa-sigma,fa-sign-hanging,fa-sign,fa-signal-5,fa-signal-perfect,fa-signal,fa-signal-alt-4,fa-signal-alt,fa-signal-bars-strong,fa-signal-bars,fa-signal-alt-2,fa-signal-bars-fair,fa-signal-alt-3,fa-signal-bars-good,fa-signal-alt-slash,fa-signal-bars-slash,fa-signal-alt-1,fa-signal-bars-weak,fa-signal-2,fa-signal-fair,fa-signal-3,fa-signal-good,fa-signal-slash,fa-signal-stream,fa-signal-stream-slash,fa-signal-4,fa-signal-strong,fa-signal-1,fa-signal-weak,fa-signature,fa-map-signs,fa-signs-post,fa-sim-card,fa-sim-cards,fa-sink,fa-siren,fa-siren-on,fa-sitemap,fa-skeleton,fa-skull,fa-skull-cow,fa-skull-crossbones,fa-slash,fa-slash-back,fa-slash-forward,fa-sleigh,fa-slider,fa-sliders-h,fa-sliders,fa-sliders-simple,fa-sliders-up,fa-sliders-v,fa-smog,fa-smoke,fa-smoking,fa-snake,fa-snooze,fa-zzz,fa-snow-blowing,fa-snowflake,fa-snowflakes,fa-snowman,fa-frosty-head,fa-snowman-head,fa-snowplow,fa-soap,fa-socks,fa-solar-panel,fa-solar-system,fa-sort,fa-unsorted,fa-sort-desc,fa-sort-down,fa-sort-asc,fa-sort-up,fa-spa,fa-space-station-moon,fa-space-station-moon-alt,fa-space-station-moon-construction,fa-spade,fa-pastafarianism,fa-spaghetti-monster-flying,fa-sparkles,fa-speaker,fa-speakers,fa-spell-check,fa-spider,fa-spider-black-widow,fa-spider-web,fa-spinner,fa-spinner-third,fa-split,fa-splotch,fa-spoon,fa-utensil-spoon,fa-spray-can,fa-air-freshener,fa-spray-can-sparkles,fa-sprinkler,fa-square,fa-square-0,fa-square-1,fa-square-2,fa-square-3,fa-square-4,fa-square-5,fa-square-6,fa-square-7,fa-square-8,fa-square-9,fa-square-a,fa-square-ampersand,fa-arrow-square-down,fa-square-arrow-down,fa-square-arrow-down-left,fa-square-arrow-down-right,fa-arrow-square-left,fa-square-arrow-left,fa-arrow-square-right,fa-square-arrow-right,fa-arrow-square-up,fa-square-arrow-up,fa-square-arrow-up-left,fa-external-link-square,fa-square-arrow-up-right,fa-square-b,fa-square-bolt,fa-square-c,fa-caret-square-down,fa-square-caret-down,fa-caret-square-left,fa-square-caret-left,fa-caret-square-right,fa-square-caret-right,fa-caret-square-up,fa-square-caret-up,fa-check-square,fa-square-check,fa-chevron-square-down,fa-square-chevron-down,fa-chevron-square-left,fa-square-chevron-left,fa-chevron-square-right,fa-square-chevron-right,fa-chevron-square-up,fa-square-chevron-up,fa-square-code,fa-square-d,fa-square-dashed,fa-square-divide,fa-dollar-square,fa-square-dollar,fa-usd-square,fa-arrow-alt-square-down,fa-square-down,fa-square-down-left,fa-square-down-right,fa-square-e,fa-square-ellipsis,fa-square-ellipsis-vertical,fa-envelope-square,fa-square-envelope,fa-exclamation-square,fa-square-exclamation,fa-square-f,fa-box-fragile,fa-square-fragile,fa-square-wine-glass-crack,fa-square-full,fa-square-g,fa-h-square,fa-square-h,fa-heart-square,fa-square-heart,fa-square-i,fa-info-square,fa-square-info,fa-square-j,fa-square-k,fa-square-l,fa-arrow-alt-square-left,fa-square-left,fa-square-m,fa-minus-square,fa-square-minus,fa-square-n,fa-square-o,fa-square-p,fa-parking,fa-square-parking,fa-parking-slash,fa-square-parking-slash,fa-pen-square,fa-pencil-square,fa-square-pen,fa-phone-square,fa-square-phone,fa-phone-square-alt,fa-square-phone-flip,fa-phone-square-down,fa-square-phone-hangup,fa-plus-square,fa-square-plus,fa-poll-h,fa-square-poll-horizontal,fa-poll,fa-square-poll-vertical,fa-square-q,fa-question-square,fa-square-question,fa-square-quote,fa-square-r,fa-arrow-alt-square-right,fa-square-right,fa-square-root,fa-square-root-alt,fa-square-root-variable,fa-rss-square,fa-square-rss,fa-square-s,fa-share-alt-square,fa-square-share-nodes,fa-sliders-h-square,fa-square-sliders,fa-sliders-v-square,fa-square-sliders-vertical,fa-square-small,fa-square-star,fa-square-t,fa-square-terminal,fa-box-up,fa-square-this-way-up,fa-square-u,fa-arrow-alt-square-up,fa-square-up,fa-square-up-left,fa-external-link-square-alt,fa-square-up-right,fa-square-user,fa-square-v,fa-square-w,fa-square-x,fa-square-xmark,fa-times-square,fa-xmark-square,fa-square-y,fa-square-z,fa-squirrel,fa-staff,fa-stairs,fa-stamp,fa-rectangle-sd,fa-standard-definition,fa-star,fa-star-and-crescent,fa-star-christmas,fa-star-exclamation,fa-star-half,fa-star-half-alt,fa-star-half-stroke,fa-star-of-david,fa-star-of-life,fa-star-sharp,fa-star-sharp-half,fa-star-sharp-half-alt,fa-star-sharp-half-stroke,fa-star-shooting,fa-starfighter,fa-starfighter-alt,fa-starfighter-twin-ion-engine,fa-starfighter-alt-advanced,fa-starfighter-twin-ion-engine-advanced,fa-stars,fa-starship,fa-starship-freighter,fa-steak,fa-steering-wheel,fa-gbp,fa-pound-sign,fa-sterling-sign,fa-stethoscope,fa-stocking,fa-stomach,fa-stop,fa-stopwatch,fa-stopwatch-20,fa-store,fa-store-slash,fa-strawberry,fa-street-view,fa-stretcher,fa-strikethrough,fa-stroopwafel,fa-subscript,fa-suitcase,fa-medkit,fa-suitcase-medical,fa-suitcase-rolling,fa-sun,fa-sun-alt,fa-sun-bright,fa-sun-cloud,fa-sun-dust,fa-sun-haze,fa-sunglasses,fa-sunrise,fa-sunset,fa-superscript,fa-swatchbook,fa-sword,fa-sword-laser,fa-sword-laser-alt,fa-swords,fa-swords-laser,fa-icons-alt,fa-symbols,fa-synagogue,fa-syringe,fa-t,fa-table,fa-table-cells,fa-th,fa-table-cells-large,fa-th-large,fa-columns,fa-table-columns,fa-table-layout,fa-table-list,fa-th-list,fa-table-picnic,fa-table-pivot,fa-rows,fa-table-rows,fa-ping-pong-paddle-ball,fa-table-tennis-paddle-ball,fa-table-tennis,fa-table-tree,fa-tablet-android,fa-tablet,fa-tablet-button,fa-tablet-rugged,fa-tablet-android-alt,fa-tablet-screen,fa-tablet-alt,fa-tablet-screen-button,fa-tablets,fa-digital-tachograph,fa-tachograph-digital,fa-taco,fa-tag,fa-tags,fa-tally-5,fa-tally,fa-tally-1,fa-tally-2,fa-tally-3,fa-tally-4,fa-tape,fa-cab,fa-taxi,fa-taxi-bus,fa-teeth,fa-teeth-open,fa-telescope,fa-temperature-arrow-down,fa-temperature-down,fa-temperature-arrow-up,fa-temperature-up,fa-temperature-0,fa-temperature-empty,fa-thermometer-0,fa-thermometer-empty,fa-temperature-4,fa-temperature-full,fa-thermometer-4,fa-thermometer-full,fa-temperature-2,fa-temperature-half,fa-thermometer-2,fa-thermometer-half,fa-temperature-high,fa-temperature-list,fa-temperature-low,fa-temperature-1,fa-temperature-quarter,fa-thermometer-1,fa-thermometer-quarter,fa-temperature-frigid,fa-temperature-snow,fa-temperature-hot,fa-temperature-sun,fa-temperature-3,fa-temperature-three-quarters,fa-thermometer-3,fa-thermometer-three-quarters,fa-tenge-sign,fa-tenge,fa-tennis-ball,fa-terminal,fa-text,fa-text-height,fa-text-size,fa-remove-format,fa-text-slash,fa-text-width,fa-thermometer,fa-theta,fa-thought-bubble,fa-thumbs-down,fa-thumbs-up,fa-thumb-tack,fa-thumbtack,fa-tick,fa-ticket,fa-ticket-airline,fa-ticket-alt,fa-ticket-simple,fa-tickets-airline,fa-tilde,fa-timeline,fa-timeline-arrow,fa-timer,fa-tire,fa-tire-flat,fa-tire-pressure-warning,fa-tire-rugged,fa-toggle-off,fa-toggle-on,fa-toilet,fa-toilet-paper,fa-toilet-paper-alt,fa-toilet-paper-blank,fa-toilet-paper-blank-under,fa-toilet-paper-reverse-alt,fa-toilet-paper-slash,fa-toilet-paper-reverse,fa-toilet-paper-under,fa-toilet-paper-reverse-slash,fa-toilet-paper-under-slash,fa-tomato,fa-tombstone,fa-tombstone-alt,fa-tombstone-blank,fa-toolbox,fa-tooth,fa-toothbrush,fa-torii-gate,fa-tornado,fa-broadcast-tower,fa-tower-broadcast,fa-tower-control,fa-tractor,fa-trademark,fa-traffic-cone,fa-traffic-light,fa-traffic-light-go,fa-traffic-light-slow,fa-traffic-light-stop,fa-trailer,fa-train,fa-subway,fa-train-subway,fa-subway-tunnel,fa-train-subway-tunnel,fa-train-tram,fa-tram,fa-transformer-bolt,fa-transgender,fa-transgender-alt,fa-transporter,fa-transporter-1,fa-transporter-2,fa-transporter-3,fa-transporter-4,fa-transporter-5,fa-transporter-6,fa-transporter-7,fa-transporter-empty,fa-trash,fa-trash-arrow-up,fa-trash-restore,fa-trash-alt,fa-trash-can,fa-trash-can-arrow-up,fa-trash-restore-alt,fa-trash-can-check,fa-trash-can-clock,fa-trash-can-list,fa-trash-can-plus,fa-trash-alt-slash,fa-trash-can-slash,fa-trash-can-arrow-turn-left,fa-trash-can-undo,fa-trash-undo-alt,fa-trash-can-xmark,fa-trash-check,fa-trash-clock,fa-trash-list,fa-trash-plus,fa-trash-slash,fa-trash-arrow-turn-left,fa-trash-undo,fa-trash-xmark,fa-treasure-chest,fa-tree,fa-tree-christmas,fa-tree-alt,fa-tree-deciduous,fa-tree-decorated,fa-tree-large,fa-tree-palm,fa-trees,fa-triangle,fa-exclamation-triangle,fa-triangle-exclamation,fa-warning,fa-triangle-instrument,fa-triangle-music,fa-construction,fa-triangle-person-digging,fa-trophy,fa-trophy-alt,fa-trophy-star,fa-truck,fa-shipping-timed,fa-truck-clock,fa-truck-container,fa-truck-container-empty,fa-shipping-fast,fa-truck-fast,fa-truck-flatbed,fa-truck-front,fa-ambulance,fa-truck-medical,fa-truck-monster,fa-truck-moving,fa-truck-pickup,fa-truck-plow,fa-truck-ramp,fa-truck-loading,fa-truck-ramp-box,fa-truck-couch,fa-truck-ramp-couch,fa-truck-tow,fa-trumpet,fa-tshirt,fa-teletype,fa-tty,fa-teletype-answer,fa-tty-answer,fa-tugrik-sign,fa-turkey,fa-try,fa-turkish-lira-sign,fa-turkish-lira,fa-level-down-alt,fa-turn-down,fa-turn-down-left,fa-level-up-alt,fa-turn-up,fa-turntable,fa-turtle,fa-television,fa-tv-alt,fa-tv,fa-tv-music,fa-tv-retro,fa-typewriter,fa-u,fa-ufo,fa-ufo-beam,fa-umbrella,fa-umbrella-beach,fa-umbrella-alt,fa-umbrella-simple,fa-underline,fa-unicorn,fa-union,fa-universal-access,fa-unlock,fa-unlock-alt,fa-unlock-keyhole,fa-arrow-alt-up,fa-up,fa-arrows-alt-v,fa-up-down,fa-arrows-alt,fa-up-down-left-right,fa-arrow-alt-from-bottom,fa-up-from-line,fa-up-left,fa-long-arrow-alt-up,fa-up-long,fa-up-right,fa-expand-alt,fa-up-right-and-down-left-from-center,fa-external-link-alt,fa-up-right-from-square,fa-arrow-alt-to-top,fa-up-to-line,fa-upload,fa-usb-drive,fa-user,fa-user-alien,fa-user-astronaut,fa-user-bounty-hunter,fa-user-check,fa-user-clock,fa-user-cowboy,fa-user-crown,fa-user-doctor,fa-user-md,fa-user-doctor-message,fa-user-md-chat,fa-user-cog,fa-user-gear,fa-user-graduate,fa-user-friends,fa-user-group,fa-user-group-crown,fa-users-crown,fa-user-headset,fa-user-construction,fa-user-hard-hat,fa-user-helmet-safety,fa-user-injured,fa-user-alt,fa-user-large,fa-user-alt-slash,fa-user-large-slash,fa-user-lock,fa-user-minus,fa-user-music,fa-user-ninja,fa-user-nurse,fa-user-edit,fa-user-pen,fa-user-pilot,fa-user-pilot-tie,fa-user-plus,fa-user-police,fa-user-police-tie,fa-user-robot,fa-user-secret,fa-user-shakespeare,fa-user-shield,fa-user-slash,fa-user-tag,fa-user-tie,fa-user-unlock,fa-user-visor,fa-user-times,fa-user-xmark,fa-group,fa-users,fa-users-cog,fa-users-gear,fa-users-medical,fa-users-slash,fa-cutlery,fa-utensils,fa-utility-pole,fa-utility-pole-double,fa-v,fa-vacuum,fa-vacuum-robot,fa-value-absolute,fa-shuttle-van,fa-van-shuttle,fa-vault,fa-vector-circle,fa-vector-polygon,fa-vector-square,fa-venus,fa-venus-double,fa-venus-mars,fa-vest,fa-vest-patches,fa-vial,fa-vials,fa-video-camera,fa-video,fa-video-arrow-down-left,fa-video-arrow-up-right,fa-video-plus,fa-video-slash,fa-vihara,fa-violin,fa-virus,fa-virus-slash,fa-viruses,fa-voicemail,fa-volcano,fa-volleyball-ball,fa-volume-medium,fa-volume,fa-volume-high,fa-volume-up,fa-volume-down,fa-volume-low,fa-volume-off,fa-volume-slash,fa-volume-mute,fa-volume-times,fa-volume-xmark,fa-vr-cardboard,fa-w,fa-wagon-covered,fa-walker,fa-walkie-talkie,fa-wallet,fa-wand,fa-magic,fa-wand-magic,fa-magic-wand-sparkles,fa-wand-magic-sparkles,fa-wand-sparkles,fa-warehouse,fa-warehouse-alt,fa-warehouse-full,fa-washer,fa-washing-machine,fa-watch,fa-watch-apple,fa-watch-calculator,fa-watch-fitness,fa-watch-smart,fa-water,fa-water-arrow-down,fa-water-lower,fa-water-arrow-up,fa-water-rise,fa-ladder-water,fa-swimming-pool,fa-water-ladder,fa-watermelon-slice,fa-heart-rate,fa-wave-pulse,fa-wave-sine,fa-wave-square,fa-wave-triangle,fa-waveform,fa-waveform-lines,fa-weight-hanging,fa-weight-scale,fa-weight,fa-whale,fa-wheat,fa-wheat-alt,fa-wheat-awn,fa-wheat-awn-slash,fa-wheat-slash,fa-wheelchair,fa-wheelchair-alt,fa-wheelchair-move,fa-glass-whiskey,fa-whiskey-glass,fa-glass-whiskey-rocks,fa-whiskey-glass-ice,fa-whistle,fa-wifi-3,fa-wifi-strong,fa-wifi,fa-wifi-exclamation,fa-wifi-2,fa-wifi-fair,fa-wifi-slash,fa-wifi-1,fa-wifi-weak,fa-wind,fa-wind-turbine,fa-wind-circle-exclamation,fa-wind-warning,fa-window,fa-window-alt,fa-window-flip,fa-window-frame,fa-window-frame-open,fa-window-maximize,fa-window-minimize,fa-window-restore,fa-windsock,fa-wine-bottle,fa-wine-glass,fa-fragile,fa-wine-glass-crack,fa-wine-glass-alt,fa-wine-glass-empty,fa-krw,fa-won-sign,fa-won,fa-wreath,fa-wrench,fa-wrench-simple,fa-x,fa-x-ray,fa-close,fa-multiply,fa-remove,fa-times,fa-xmark,fa-times-to-slot,fa-vote-nay,fa-xmark-to-slot,fa-y,fa-cny,fa-jpy,fa-rmb,fa-yen-sign,fa-yen,fa-yin-yang,fa-z,fa-sr-only,fa-sr-only-focusable:not(:focus),sr-only,sr-only-focusable:not(:focus),fa-brands,fab,fa-500px,fa-accessible-icon,fa-accusoft,fa-acquisitions-incorporated,fa-adn,fa-adversal,fa-affiliatetheme,fa-airbnb,fa-algolia,fa-alipay,fa-amazon,fa-amazon-pay,fa-amilia,fa-android,fa-angellist,fa-angrycreative,fa-angular,fa-app-store,fa-app-store-ios,fa-apper,fa-apple,fa-apple-pay,fa-artstation,fa-asymmetrik,fa-atlassian,fa-audible,fa-autoprefixer,fa-avianex,fa-aviato,fa-aws,fa-bandcamp,fa-battle-net,fa-behance,fa-behance-square,fa-bimobject,fa-bitbucket,fa-bitcoin,fa-bity,fa-black-tie,fa-blackberry,fa-blogger,fa-blogger-b,fa-bluetooth,fa-bluetooth-b,fa-bootstrap,fa-btc,fa-buffer,fa-buromobelexperte,fa-buy-n-large,fa-buysellads,fa-canadian-maple-leaf,fa-cc-amazon-pay,fa-cc-amex,fa-cc-apple-pay,fa-cc-diners-club,fa-cc-discover,fa-cc-jcb,fa-cc-mastercard,fa-cc-paypal,fa-cc-stripe,fa-cc-visa,fa-centercode,fa-centos,fa-chrome,fa-chromecast,fa-cloudflare,fa-cloudscale,fa-cloudsmith,fa-cloudversify,fa-codepen,fa-codiepie,fa-confluence,fa-connectdevelop,fa-contao,fa-cotton-bureau,fa-cpanel,fa-creative-commons,fa-creative-commons-by,fa-creative-commons-nc,fa-creative-commons-nc-eu,fa-creative-commons-nc-jp,fa-creative-commons-nd,fa-creative-commons-pd,fa-creative-commons-pd-alt,fa-creative-commons-remix,fa-creative-commons-sa,fa-creative-commons-sampling,fa-creative-commons-sampling-plus,fa-creative-commons-share,fa-creative-commons-zero,fa-critical-role,fa-css3,fa-css3-alt,fa-cuttlefish,fa-d-and-d,fa-d-and-d-beyond,fa-dailymotion,fa-dashcube,fa-deezer,fa-delicious,fa-deploydog,fa-deskpro,fa-dev,fa-deviantart,fa-dhl,fa-diaspora,fa-digg,fa-digital-ocean,fa-discord,fa-discourse,fa-dochub,fa-docker,fa-draft2digital,fa-dribbble,fa-dribbble-square,fa-dropbox,fa-drupal,fa-dyalog,fa-earlybirds,fa-ebay,fa-edge,fa-edge-legacy,fa-elementor,fa-ello,fa-ember,fa-empire,fa-envira,fa-erlang,fa-ethereum,fa-etsy,fa-evernote,fa-expeditedssl,fa-facebook,fa-facebook-f,fa-facebook-messenger,fa-facebook-square,fa-fantasy-flight-games,fa-fedex,fa-fedora,fa-figma,fa-firefox,fa-firefox-browser,fa-first-order,fa-first-order-alt,fa-firstdraft,fa-flickr,fa-flipboard,fa-fly,fa-font-awesome-flag,fa-font-awesome-logo-full,fa-font-awesome,fa-fonticons,fa-fonticons-fi,fa-fort-awesome,fa-fort-awesome-alt,fa-forumbee,fa-foursquare,fa-free-code-camp,fa-freebsd,fa-fulcrum,fa-galactic-republic,fa-galactic-senate,fa-get-pocket,fa-gg,fa-gg-circle,fa-git,fa-git-alt,fa-git-square,fa-github,fa-github-alt,fa-github-square,fa-gitkraken,fa-gitlab,fa-gitter,fa-glide,fa-glide-g,fa-gofore,fa-goodreads,fa-goodreads-g,fa-google,fa-google-drive,fa-google-pay,fa-google-play,fa-google-plus,fa-google-plus-g,fa-google-plus-square,fa-google-wallet,fa-gratipay,fa-grav,fa-gripfire,fa-grunt,fa-guilded,fa-gulp,fa-hacker-news,fa-hacker-news-square,fa-hackerrank,fa-hips,fa-hire-a-helper,fa-hive,fa-hooli,fa-hornbill,fa-hotjar,fa-houzz,fa-html5,fa-hubspot,fa-ideal,fa-imdb,fa-innosoft,fa-instagram,fa-instagram-square,fa-instalod,fa-intercom,fa-internet-explorer,fa-invision,fa-ioxhost,fa-itch-io,fa-itunes,fa-itunes-note,fa-java,fa-jedi-order,fa-jenkins,fa-jira,fa-joget,fa-joomla,fa-js,fa-js-square,fa-jsfiddle,fa-kaggle,fa-keybase,fa-keycdn,fa-kickstarter,fa-kickstarter-k,fa-korvue,fa-laravel,fa-lastfm,fa-lastfm-square,fa-leanpub,fa-less,fa-line,fa-linkedin,fa-linkedin-in,fa-linode,fa-linux,fa-lyft,fa-magento,fa-mailchimp,fa-mandalorian,fa-markdown,fa-mastodon,fa-maxcdn,fa-mdb,fa-medapps,fa-medium-m,fa-medium,fa-medrt,fa-meetup,fa-megaport,fa-mendeley,fa-microblog,fa-microsoft,fa-mix,fa-mixcloud,fa-mixer,fa-mizuni,fa-modx,fa-monero,fa-napster,fa-neos,fa-nimblr,fa-node,fa-node-js,fa-npm,fa-ns8,fa-nutritionix,fa-octopus-deploy,fa-odnoklassniki,fa-odnoklassniki-square,fa-old-republic,fa-opencart,fa-openid,fa-opera,fa-optin-monster,fa-orcid,fa-osi,fa-page4,fa-pagelines,fa-palfed,fa-patreon,fa-paypal,fa-penny-arcade,fa-perbyte,fa-periscope,fa-phabricator,fa-phoenix-framework,fa-phoenix-squadron,fa-php,fa-pied-piper,fa-pied-piper-alt,fa-pied-piper-hat,fa-pied-piper-pp,fa-pied-piper-square,fa-pinterest,fa-pinterest-p,fa-pinterest-square,fa-playstation,fa-product-hunt,fa-pushed,fa-python,fa-qq,fa-quinscape,fa-quora,fa-r-project,fa-raspberry-pi,fa-ravelry,fa-react,fa-reacteurope,fa-readme,fa-rebel,fa-red-river,fa-reddit,fa-reddit-alien,fa-reddit-square,fa-redhat,fa-renren,fa-replyd,fa-researchgate,fa-resolving,fa-rev,fa-rocketchat,fa-rockrms,fa-rust,fa-safari,fa-salesforce,fa-sass,fa-schlix,fa-scribd,fa-searchengin,fa-sellcast,fa-sellsy,fa-servicestack,fa-shirtsinbulk,fa-shopify,fa-shopware,fa-simplybuilt,fa-sistrix,fa-sith,fa-sketch,fa-skyatlas,fa-skype,fa-slack-hash,fa-slack,fa-slideshare,fa-snapchat-ghost,fa-snapchat,fa-snapchat-square,fa-soundcloud,fa-sourcetree,fa-speakap,fa-speaker-deck,fa-spotify,fa-square-font-awesome,fa-font-awesome-alt,fa-square-font-awesome-stroke,fa-squarespace,fa-stack-exchange,fa-stack-overflow,fa-stackpath,fa-staylinked,fa-steam,fa-steam-square,fa-steam-symbol,fa-sticker-mule,fa-strava,fa-stripe,fa-stripe-s,fa-studiovinari,fa-stumbleupon,fa-stumbleupon-circle,fa-superpowers,fa-supple,fa-suse,fa-swift,fa-symfony,fa-teamspeak,fa-telegram-plane,fa-telegram,fa-tencent-weibo,fa-the-red-yeti,fa-themeco,fa-themeisle,fa-think-peaks,fa-tiktok,fa-trade-federation,fa-trello,fa-tripadvisor,fa-tumblr,fa-tumblr-square,fa-twitch,fa-twitter,fa-twitter-square,fa-typo3,fa-uber,fa-ubuntu,fa-uikit,fa-umbraco,fa-uncharted,fa-uniregistry,fa-unity,fa-unsplash,fa-untappd,fa-ups,fa-usb,fa-usps,fa-ussunnah,fa-vaadin,fa-viacoin,fa-viadeo,fa-viadeo-square,fa-viber,fa-vimeo,fa-vimeo-square,fa-vimeo-v,fa-vine,fa-vk,fa-vnv,fa-vuejs,fa-watchman-monitoring,fa-waze,fa-weebly,fa-weibo,fa-weixin,fa-whatsapp,fa-whatsapp-square,fa-whmcs,fa-wikipedia-w,fa-windows,fa-wirsindhanderk,fa-wsh,fa-wix,fa-wizards-of-the-coast,fa-wodu,fa-wolf-pack-battalion,fa-wordpress,fa-wordpress-simple,fa-wpbeginner,fa-wpexplorer,fa-wpforms,fa-wpressr,fa-xbox,fa-xing,fa-xing-square,fa-y-combinator,fa-yahoo,fa-yammer,fa-yandex,fa-yandex-international,fa-yarn,fa-yelp,fa-yoast,fa-youtube,fa-youtube-square,fa-zhihu,fa-duotone,fad,fa-swap-opacity,fa-swap-opacity ,fa-fw,fa-light,fal,fa-regular,far,fa-solid,fas,fa-thin,fat";
                string[] fontarr = Font.Split(',');
                foreach (string Item in fontarr)
                {
                    IconList.Add(new SelectListItem() { Text = Item, Value = "fa " + Item });
                }

                HttpContext.Current.Session["CachedIconList"] = IconList;
            }

            return (List<SelectListItem>)HttpContext.Current.Session["CachedIconList"];
        }



        public static string IconName(CoreDefine.Entities Entity)
        {
            switch (Entity)
            {
                case CoreDefine.Entities.جدول:
                    return "k-icon k-i-table";
                case CoreDefine.Entities.فیلد:
                    return "k-icon k-i-kpi-status-deny";
                case CoreDefine.Entities.دکمه_رویداد_جدول:
                    return "k-icon k-i-button";
                case CoreDefine.Entities.فیلد_محاسباتی:
                    return "k-icon k-i-table-column-insert-right";
                case CoreDefine.Entities.فیلد_نمایشی:
                    return "k-icon k-i-eye";
                case CoreDefine.Entities.نقش_کاربر:
                    return "k-icon k-i-myspace";
                case CoreDefine.Entities.کاربر:
                    return "k-icon k-i-user";
                case CoreDefine.Entities.گزارش:
                    return "k-icon k-i-graph";
                case CoreDefine.Entities.پارامتر_گزارش:
                    return "k-icon k-i-edit-tools";
                case CoreDefine.Entities.فرم_ورود_اطلاعات:
                    return "k-icon k-i-form-element";
                case CoreDefine.Entities.فرم_جستجو:
                    return "k-icon k-i-search";
                case CoreDefine.Entities.عبارت_ویژه:
                    return "k-icon k-i-change-manually";
                case CoreDefine.Entities.فرآیند:
                    return "k-icon k-i-inherited";
                case CoreDefine.Entities.مرحله_فرآیند:
                    return "k-icon k-i-connector";
                case CoreDefine.Entities.ارجاع_مرحله_فرآیند:
                    return "k-icon k-i-forward";
                case CoreDefine.Entities.رویداد_نمایش_فیلد:
                    return "k-icon k-i-code";
                case CoreDefine.Entities.رویداد_مرحله_فرآیند:
                    return "k-icon k-i-code";
                case CoreDefine.Entities.رویداد_فرم_جدولی:
                    return "k-icon k-i-code";
                case CoreDefine.Entities.رویداد_جدول:
                    return "k-icon k-i-code";
                case CoreDefine.Entities.فایل_عمومی:
                    return "k-icon k-i-file-data";
                case CoreDefine.Entities.داشبورد:
                    return "k-icon k-i-chart-doughnut";
                case CoreDefine.Entities.زیر_بخش_داشبورد:
                    return "k-icon k-i-subreport";
                case CoreDefine.Entities.ادغام_داشبورد:
                    return "fa fa-chart-network";
                case CoreDefine.Entities.تنظیمات_پرداخت:
                    return "fa fa-credit-card"; 
                case CoreDefine.Entities.وب_سرویس:
                    return "fa fa-at";
                case CoreDefine.Entities.تنظیمات_عمومی:
                    return "k-icon k-i-gears";
                case CoreDefine.Entities.تنظیمات_مدیر_سیستم:
                    return "k-icon k-i-gears";
                case CoreDefine.Entities.ضمیمه_جدول:
                    return "k-icon k-i-attachment"; 
                case CoreDefine.Entities.ارتباط_با_وبسایت:
                    return "k-icon k-i-globe-link";
                case CoreDefine.Entities.پایگاه_داده:
                    return "k-icon k-i-data";
                case CoreDefine.Entities.تابع_جدولی:
                    return "k-icon k-i-formula-fx";
                case CoreDefine.Entities.پارامتر_وب_سرویس:
                case CoreDefine.Entities.پارامتر_تابع:
                    return "k-icon k-i-parameters";
                case CoreDefine.Entities.رویداد_عمومی:
                    return "k-icon k-i-calendar";
                case CoreDefine.Entities.فیلد_گروهبندی:
                    return "k-icon k-i-group";
                case CoreDefine.Entities.رنگ_سطر_جدول:
                    return "k-icon k-i-gap-row";
                case CoreDefine.Entities.فیلد_جستجو:
                    return "fa fa-file-search";
                case CoreDefine.Entities.فرم_دکمه_جدید:
                    return "fa fa-plus-square";
                default:
                    return "";
            }
        }
    }
}